### ISSUE TITLE
debugger problem with 2.0.1-beta.33 (30,31,32)

### ISSUE THREAD

**Issue by alexfurmanov** [Azure/azure-functions-nodejs-worker#105]
# Issue Description:
### Environment
```
$ uname -a
Linux alx-jeeng 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

$ node -v
v8.9.4

$ func -v
2.0.1-beta.33

VSCode:
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:40:20.190Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
```
### Steps to reproduce issue
1. open VSCode
2. run _npm start_ in console
3. press F5 to connect debugger

### Describe the results you received
error popup window with message:
_Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:5858)._

### What is inside your .vscode/launch.json file
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to Azure Functions",
      "type": "node",
      "request": "attach",
      "port": 5858,
      "protocol": "inspector"
    },
  ]
}
```

## Known workarounds:
```sudo npm i -g azure-functions-core-tools@2.0.1-beta.29 --unsafe-perm true```

**Comment by EricJizbaMSFT** [comment]
@alexfurmanov just released an update to the functions extension in VS Code that asks to update your project the next time you open it. We have to do this because of breaking changes in the functions runtime. You can see https://aka.ms/AA1vrxa for more information, including manual instructions for updating your project
