### ISSUE TITLE
Show error if context.done() is missing

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-nodejs-worker#106]
If context.done() is missing we should show warning to the user. As of now, invoking a function without context.done() hangs and eventually timesout.

**Comment by ltouro** [comment]
Having a problem with ```"context.done" is already called``` in one of my functions when an error is catched. I see two contradictory information is this repo. Can you please clarify the right path?

In https://github.com/Azure/azure-functions-nodejs-worker/issues/94: 

```
Don't use the context.done() method
```

In https://github.com/Azure/azure-functions-nodejs-worker/issues/106
```
If context.done() is missing we should show warning to the user. As of now, invoking a function without context.done() hangs and eventually timesout.
```

Pseudo example:
```js
module.exports = function(context, req) {
service.doSomething()
   .then(() => {
      context.log("context.done below will work normally. If not called, will hang until timeout");
   })
   .catch((err) => {
      context.log("but if got an err, this will cause 'context.done is already called'"):
   })
   .then(context.done)
  }
```

Logs:

```
[03/09/2018 14:51:02] 2018-09-03T14:51:02.928Z - GET /auth/login [SUCCESS]
[03/09/2018 14:51:02] 2018-09-03T14:51:02.929Z - ERR - {"error":"TypeError: Cannot read property 'split' of undefined"}
[03/09/2018 14:51:02] Error: 'done' has already been called. Please check your script for extraneous calls to 'done'.
[03/09/2018 14:51:02]
```

**Comment by mhoeger** [comment]
This isn't well documented (https://github.com/Azure/azure-functions-nodejs-worker/issues/94), but if your exported function is returning a promise, then context.done is implicitly called. So no need to call context.done yourself :) That's a good point though that the error message could clearly say that. i'll retitle to track that aspect of this issue

**Comment by ltouro** [comment]
@mhoeger Fixed the issue by returning the promise (instead of void). Without that, the system can't call context.done automatically. Also, I using a sync function, not async. 

Notwithstanding, still can't understand how I ended up with a **context.done** called twice, since no promise was being returned. Could not set up a simple example to show that, so I problably doing something wrong. 

Thanks for the feedback.

**Comment by paulbatum** [comment]
@mhoeger should this issue stay open? I'm unclear what its tracking at this point.

**Comment by mhoeger** [comment]
@paulbatum - i think this should stay open, although not necessary for GA. The most recent issue in comments is being tracked here: https://github.com/Azure/azure-functions-nodejs-worker/issues/124

**Comment by brandonh-msft** [comment]
FWIW, This is being tracked by CSE as a P1
<details><summary>Internal Tracking</summary>203617</details>

cc @theangellmethod

**Comment by ejizba** [comment]
Closing this because it's stale. context.done() has been discouraged for a while now in favor of async and we already have several warnings/detectors for it.
