### ISSUE TITLE
context.done called twice error message confusing for async / promise returning functions

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#124]
Today, error message is: `Error: 'done' has already been called. Please check your script for extraneous calls to 'done'.`

This is confusing when the first 'done' has been called due to the function being async or the function returning a promise. If we can tell which scenario it is, our error message should be specific to this case. (note: it should be easy to tell if the 'done' call was internal or not).

**Comment by gunzip** [comment]
sorry to bump this issue but there are a lot of examples in the docs that have an async handler + a call to context.done(), ie: https://docs.microsoft.com/it-it/azure/azure-functions/functions-bindings-warmup?tabs=javascript#trigger---example (just to quote one)

is this an accepted pattern in v2 ?

**Comment by mhoeger** [comment]
@gunzip - thanks for pointing that out! this definitely isn't a recommended pattern. We recommend either use async only or callbacks only (using context.done()). I'll try to change those
