### ISSUE TITLE
Better Error Message when dependency not found

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/azure-functions-nodejs-worker#129]
Customer got the following error message:

2018-09-17T18:35:05.120 [Information] Executing 'Functions.processor' (Reason='This function was programmatically called via the host APIs.', Id=2135d642-8a26-4bd7-b828-dc97eb3ba720)
2018-09-17T18:35:05.159 [Error] Executed 'Functions.processor' (Failed, Id=2135d642-8a26-4bd7-b828-dc97eb3ba720)

When I looked at the logs, it was more verbose:

Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.processor ---> Microsoft.Azure.WebJobs.Script.Rpc.RpcException : Result: Failure
Exception: Worker was unable to load function processor: 'Error: Cannot find module 'xpath''
Stack: Error: Cannot find module 'xpath'
<stack trace>

Customer had much difficulty debugging, and only was able to figure out that they accidentally forgotten about the above dependency once I looked up the above. We should fix this.

**Comment by mhoeger** [comment]
Fixed in [latest release](https://github.com/Azure/azure-functions-host/releases/tag/v2.0.12134)
