### ISSUE TITLE
Expose list of output bindings on the context object

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-nodejs-worker#132]
As part of function load request, functions host sends a list of input and output bindings
[LanguageWorkerChannel.cs#L352](https://github.com/Azure/azure-functions-host/blob/8f712eba4a95d1e57b93c98532f1ce02def89d83/src/WebJobs.Script/Rpc/LanguageWorkerChannel.cs#L352)
And NodeJS worker  stores this information as part of [FunctionInfo.ts#L19](https://github.com/Azure/azure-functions-nodejs-worker/blob/dev/src/FunctionInfo.ts#L19)

Exposing this list on the context object will make it easier to set values to output bindings.

**Comment by pragnagopa** [comment]
cc : @kashimiz

**Comment by kashimiz** [comment]
Use case: I'm in the process of writing a module for Durable Functions in JavaScript that needs to assign information to an output binding. Ideally the user wouldn't need to specify the binding's name; the module would simply accept the context object and scan the bindings to locate the desired output binding (based on some characteristic.)

**Comment by mhoeger** [comment]
@pragnagopa @kashimiz - This sounds good! We could either:
1. Have members on the context.bindings object with value: "undefined" (since assigning values to context.bindings is one way of writing outputs and I think that "undefined" is never set for an input binding? Will have to verify)
2. Have explicit metadata elsewhere. 

One question on automatically assigning outputs - how would work for users with multiple output bindings? Or would this be constrained to one output binding per function?

**Comment by kashimiz** [comment]
@mhoeger That's a good point. 🤔 If a function has two output bindings, A and B, going with your proposed option 1 would make it impossible to determine if A or B is the orchestrationClient output binding the module is looking for.

Ideally (for the use case I'm interested in) information about the binding type (orchestrationClient, blob, cosmos, etc.) would also be exposed in some way, which makes me lean towards option 2.

**Comment by pragnagopa** [comment]
Yes. I agree exposing metadata is more helpful. @mhoeger - can you please provide sample code snippets for the proposal?

**Comment by mhoeger** [comment]
Thoughts on this structure?
```json
context: {
        bindingDefinitions: [
                {
                    type: "httpTrigger",
                    direction: "in",
                    name: "req"
                },
                {
                    direction: "out",
                    type: "http",
                    name: "res"
                },
                {
                    direction: "out",
                    type: "queue",
                    name: "firstQueueOutput"
                },
                {
                    direction: "out",
                    type: "queue",
                    name: "secondQueueOutput"
                },
                ...
        ],
        ...
}
```
Which lets people write code like this? 
```javascript
module.exports = async function (context) {
    const outputBindings = context.bindingDefinitions.filter(binding => binding.direction === "out");
    context.log(outputBindings);
    // expected output: Array [Object { direction: "out", type: "http", name: "res" }, Object { direction: "out", type: "queue", name: "firstQueueOutput" }, Object { direction: "out", type: "queue", name: "secondQueueOutput" }]
}
```

Another option: we could nest the list of bindings under context.bindingData (context.bindingData.definitions?). bindingData currently contains function invocation metadata (trigger-specific metadata and function invocation data like invocationId, sys.methodName, sys.utcNow, and sys.randGuid)

**Comment by pragnagopa** [comment]
bindingDefinitions looks good to me as well. This would be a new list with the metadata info coming from function.json and will avoid any confusion with existing bindingdata we already provide.

**Comment by kashimiz** [comment]
Offline discussion with Pragna has won me over. +1 for bindingDefinitions.
