### ISSUE TITLE
Support multi-value outputs

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-nodejs-worker#135]
For example - user should be able to write multiple messages to the same queue binding without having to define it more than once in `function.json`

**Comment by mhoeger** [comment]
I believe this is possible by returning an array of items instead of a single item. Perhaps worth documenting cc: @anthonychu

**Comment by ejizba** [comment]
This is documented for most bindings at this point. For example: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue-output?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cextensionv5&pivots=programming-language-javascript
