### ISSUE TITLE
Add Node 10.14.1

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/azure-functions-nodejs-worker#145]
Marie is going to add Node 10.13!

**Comment by maximffs** [comment]
Please notice this security update:
https://nodejs.org/en/blog/vulnerability/november-2018-security-releases/

They've identified several security vulnerabilities and released Node 10.14

**Comment by mhoeger** [comment]
Closing as the deployment is now underway (you can set WEBSITE_NODE_DEFAULT_VERSION to 10.14.1 and being tracked here: https://github.com/Azure/app-service-announcements/issues/150

Please wait for the announcement issue to be closed to know when 10.14.1 is available in all regions.
