### ISSUE TITLE
The log methods should be identified as methods

### ISSUE THREAD

**Issue by janaagaard75** [Azure/azure-functions-nodejs-worker#162]
With the current type definitions for `error`, `warn` etc. VSCode is identifying them as properties and not methods. It works out though, but I think it would be a bit nicer if they were identified as methods.

Changing `info: ILog;` to `info(...args: any[]);`

VSCode sees `info` as a property when it's written as `info: ILog;` in the type definitions file.
<img width="358" alt="property" src="https://user-images.githubusercontent.com/1769450/49857606-4c131780-fdf3-11e8-9ac9-11a0d80fce24.png">

VSCode sees `info` as a method when it's written as `info(...args: any[]);` in the type definitions file.
<img width="472" alt="method" src="https://user-images.githubusercontent.com/1769450/49857608-4e757180-fdf3-11e8-8e84-3875a6205a07.png">

I haven't made a pull request for this change, because I don't know how to generalize the writing `ILog` as a method.

**Comment by ColbyTresness** [comment]
@mhoeger
