### ISSUE TITLE
How to correlate dependencies with traces/requests in Application Insights?

### ISSUE THREAD

**Issue by IGx89** [Azure/azure-functions-nodejs-worker#176]
Hello! Currently request and trace logs are automatically sent to Application Insights by the Functions host, but any sub-requests done by the function (specifically HTTP requests out) aren't automatically logged. They can manually be logged by following the instructions at https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#custom-telemetry-in-javascript-functions, however since the host/nodejs worker doesn't provide access to the operationId used by the request and trace logs, they still don't get properly correlated.

Is there any way to retrieve the Application Insights operationId that the host uses when sending request and trace telemetry to Application Insights, so that my function app can use it when sending telemetry itself to Application Insights?

Here's my current progress:
```javascript
'use strict';

const appInsights = require('applicationinsights');
const { CorrelationContextManager } = require('applicationinsights/out/AutoCollection/CorrelationContextManager');

if (process.env.APPINSIGHTS_INSTRUMENTATIONKEY) {
    appInsights.setup()
        // don't use disk retry cache since we'll have a read-only filesystem in Azure
        .setUseDiskRetryCaching(false)
        .start();

    // Necessary for a proper application map in AI. Defaults to 'Web', when it should be the Azure resource name.
    // We should also be setting the cloud RoleInstanceId as well but haven't figured that one out yet.
    appInsights.defaultClient.context.tags[appInsights.defaultClient.context.keys.cloudRole] = process.env.WEBSITE_SITE_NAME || 'Web';
}

module.exports = (context, req) => {
    if (appInsights.defaultClient) {
        // Wrap the app logic in an Application Insights correlation context so that AI telemetry is properly correlated.
        // Currently we're only able to use invocationId instead of the host's operationId, so correlation only is possible
        // through manual queries and not through the portal's UI
        const correlationContext = CorrelationContextManager.generateContextObject(
            context.invocationId, context.invocationId, context.executionContext.functionName);

        CorrelationContextManager.runWithContext(correlationContext, () => {
            myHandler(context, req);
        });
    } else {
        myHandler(context, req);
    }
};
```

**Comment by IGx89** [comment]
HUGE bonus points if you move all this Application Insights setup into the worker, so that everyone automatically gets it!

**Comment by fabiocav** [comment]
+ @brettsam for comment

**Comment by brettsam** [comment]
This isn't working in v2 today -- it's being tracked in issue https://github.com/Azure/azure-functions-host/issues/3747.

Going to close this as it's a "duplicate" issue -- that issue will be linked here, but please do follow that issue and weigh in with anything you think we're missing in the discussion.

**Comment by IGx89** [comment]
Thanks for the reply! It sounds like that issue incorporates all of the following:

1. Lack of access to the operationId
2. No automatic dependency tracking (requires adding the appinsights package to the Node app)
3. No automatic correlation of tracked dependencies to the request when appinsights is added to the Node app to work around #2.

Assuming so, I'll happily monitor [Azure/azure-functions-host#3747](https://github.com/Azure/azure-functions-host/issues/3747) and wait that to be done.

Thanks again!
