### ISSUE TITLE
typescript typings for HttpRequest

### ISSUE THREAD

**Issue by Eikc** [Azure/azure-functions-nodejs-worker#186]
Hello :-)

Yesterday i started working on an azure http function in typescript where I needed access to the rawbody of the request to do some http request verification. It took me a while to figure out the issue but the HttpRequest.rawbody was always undefined.

It turns out that the typing for HttpRequest.rawbody is mistyped and should be HttpRequest.rawBody instead. If i manually fixed the typing to rawBody, the compiler was happy and the http verification started working.

It's the given line of the interfaces.d.ts file:
https://github.com/Azure/azure-functions-nodejs-worker/blob/dev/types/public/Interfaces.d.ts#L107

**Comment by mhoeger** [comment]
@Eikc - thank you so much for catching and reporting! A new version is published (1.0.2-beta1) that has `rawBody`.
