### ISSUE TITLE
Collect cold start data for nodeJs worker

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-nodejs-worker#19]

**Comment by paulbatum** [comment]
e.g. host.startup.outofproc.nodeworker.latency, host.startup.outofproc.grpcserverstart.latency

**Comment by pragnagopa** [comment]
Latency for startProcess method in LanguageWorkerChannel would be good capture to give us an idea on long it takes to start a language worker process. Let’s sync up offline

**Comment by mhoeger** [comment]
Resolved by https://github.com/Azure/azure-functions-host/pull/3270
