### ISSUE TITLE
Fail build if latest core tools version not found

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#192]
When we get the latest core tools version for running end to end tests (https://github.com/Azure/azure-functions-nodejs-worker/blob/dev/setup-e2e-tests.ps1), we ran into an issue where the correct version was actually not being found.

We should fail a build in this case.

**Comment by ejizba** [comment]
Closing because this is stale and the e2e test script has been significantly changed since the issue was originally filed.
