### ISSUE TITLE
Add default method types in TypeScript HttpRequest

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#193]
[req.method](https://github.com/Azure/azure-functions-nodejs-worker/blob/628042f9d114eb2472714bd4829585806b9f9166/types/public/Interfaces.d.ts#L77) is typed as `string`, but really it can only be a subset of string values: [GET,POST,HEAD,PUT,DELETE,OPTIONS,PATCH,TRACE]

**Comment by mhoeger** [comment]
cc: @johnpapa

**Comment by johnpapa** [comment]
thank you!
