### ISSUE TITLE
Remove duplication / improve organization on "context" properties

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#204]
Originally posted here: https://github.com/Azure/azure-functions-host/issues/4335
In the above issue, it was expected that `context.bindings` should include output binding names as well as input/trigger binding data. Although we could add output binding names to `context.bindings`, this issue is to track improvements around the organization and duplication of input and output binding data.

This issue tracks future breaking changes to the context object's properties

@JamieMagee as FYI. If you could also let us know what your expectations around output bindings were, and what confused you the most, it would be helpful!

**Comment by JamieMagee** [comment]
Thanks for following up with this. This doesn't necessarily need to be a breaking change right now. Updating the [documentation you linked](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#contextbindings-property) to change:

> Returns a named object that contains all your input and output data

to

>Returns a named object that contains all your input and trigger data

Would have saved me some time :smile:

**Comment by mhoeger** [comment]
@JamieMagee - omg... haha thanks, fixing now :)

**Comment by mhoeger** [comment]
Much duplication was removed on the data passing layer but not on the "context" object itself - worth considering for V4, but for V3 we tended towards limiting breaking changes.

**Comment by ejizba** [comment]
This is likely something we can address in https://github.com/Azure/azure-functions-nodejs-worker/issues/480

**Comment by ejizba** [comment]
More feedback on why we need to simplify `context` in relation to unit testing:

> Azure function handler expects context object passed as the first parameter. It encapsulates request and response objects as well as information about function bindings. Normally it's prepared by the Azure runtime but in tests, we need to craft it ourselves. There are a lot of nested objects and duplicated bits of data in the context object so assembling it manually can be tedious. Luckily there's a carefully made [stub-azure-function-context](https://github.com/willmorgan/stub-azure-function-context) module which helps with stubbing the context.

https://www.maxivanov.io/unit-testing-azure-function-with-jest-typescript/

**Comment by ejizba** [comment]
Minor details might still change, but overall this was addressed in the following commits as a part of the new programming model:

https://github.com/Azure/azure-functions-nodejs-library/commit/0aac975e880b8090c7519212df0942dd538a7228
https://github.com/Azure/azure-functions-nodejs-library/commit/15e0d384ec17e4b4ec4203356cc826c82e7df229
https://github.com/Azure/azure-functions-nodejs-library/commit/a5d678e5c0d57b6ada7e523a0afd6125bc65beb7
https://github.com/Azure/azure-functions-nodejs-library/commit/9e6a842eec8d4d29e76604a331f641a260cd1501
https://github.com/Azure/azure-functions-nodejs-library/commit/068dcf43f565f5c9052125d9e39379cd99f7ee87 

I've started a doc here with more information: https://aka.ms/AzFuncNodeV4
