### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#211]
After DevOps move

**Comment by mhoeger** [comment]
Resolved

**Comment by pragnagopa** [comment]
@mhoeger - Are the builds enabled to run nightly? If yes, can you please point me to where can i find nightly builds and test results?

**Comment by mhoeger** [comment]
Yep! https://azfunc.visualstudio.com/Azure%20Functions/_build?definitionId=10

For just looking at nightly builds, you can filter by "Requested for: Microsoft.VisualStudio.Services.TFS"
