### ISSUE TITLE
Update detector for async patterns

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#212]
Detectors can be found in the Azure Portal => Diagnose and Solve Problems.

This detector in particular looks for bad async patterns. We need to upgrade this detector to correlate to a specific function name.

**Comment by mhoeger** [comment]
blocked for now on release

**Comment by jeffhollan** [comment]
Hey @mhoeger did we complete this or is it still blocked?  Hoping to call this out in our supportability sync

**Comment by mhoeger** [comment]
Done!
