### ISSUE TITLE
GraphQl Subscriptions/Web Sockets

### ISSUE THREAD

**Issue by IgorHalfeld** [Azure/azure-functions-nodejs-worker#223]
It's not a bug, but a question...
I did this [tweet](https://twitter.com/igorhalfeld/status/1135367379146412034) asking if azure function has support to GraphQl Subscriptions but nobody said nothing and I didn't found content about it on the internet.

I wanna know if az functions has support to real time without using SignalR?

**Comment by fabiocav** [comment]
There's no built in support for real time/persistent connections with Functions today. You can have something setup when using dedicated (non-consumption) hosting models, but again, there's nothing built in to assist with that.

This is a request we've been tracking.

/cc @mattchenderson
