### ISSUE TITLE
HTTP output through context.done(null, res) is not handled correctly

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#228]
Setting HTTP output through context.done(null, res) and http output is not handled correctly. 

Example:
```javascript
let res = {
    status: 200,
    body: ["my", "array", "of", "results"],
    cookies: [ { name: "CookieName", value: "CookieValue" } ]
}
context.done(null, res);
```
Will return ```System.Collections.Generic.List`1[System.Object]``` as the body and not properly set the HTTP cookie.

We can't change this yet because the bugfix is a breaking change. Currently, this behavior is supported (which would break with the bugfix):
```javascript
let results = ["my", "array", "of", "results"];
context.done(null, results);
```
Today, this returns a 200 with the HTTP body ```[
  "my",
  "array",
  "of",
  "results"
]``` when http output binding is named `$return`

**The code fix:** In WorkerChannel.ts => invocationRequest => resultCallback => if (result.return), we need to check if it is an HTTP type and not just a generic "TypedData"

**The mitigation:** do not use context.done(err?, results?) to output results for HTTP output binding.

**Comment by dhensby** [comment]
What version of functions is this fix available in?

**Comment by mhoeger** [comment]
Functions V3 (https://github.com/Azure/azure-functions-host/releases/tag/3.0.12915). This is still a preview version of Functions, but we're targeting to get it out of preview by end of year!

**Comment by dhensby** [comment]
thanks
