### ISSUE TITLE
Uncaught Exceptions not obvious in production

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#242]
When there's an uncaught exception, we log it and it is fairly obvious in local development. However, in production and Portal development scenarios, these uncaught exceptions are fairly hidden. To the request issuer, it'll just look like the request hangs indefinitely, as in here: https://github.com/Azure/azure-functions-host/issues/4787

**Comment by mhoeger** [comment]
I'm not sure what the current status on this is, but if not yet addressed would be good to add after @soninaren 's Errors API work

**Comment by ejizba** [comment]
Fyi @alrod, this may or may not be improved by a recent PR I did: https://github.com/Azure/azure-functions-host/pull/8101 & https://github.com/Azure/azure-functions-host/pull/8102

**Comment by alrod** [comment]
The [code](https://github.com/Azure/azure-functions-nodejs-worker/blob/v3.x/src/Worker.ts#L53) logs unhandled exceptions. This was validated on the portal/app insights/kusto.
HttpTrigger returns 500.
