### ISSUE TITLE
NodeJS Worker not running ibm_db module

### ISSUE THREAD

**Issue by kyallanum** [Azure/azure-functions-nodejs-worker#248]
#### Issue Description
Whenever I am trying to use the ibm_db module in a NodeJS Azure Function, I receive the error:

2019-09-09T16:45:57.114 [Error] Executed 'Functions.testDb2' (Failed, Id=c18020f5-ddd4-46e1-9ff8-044bd8222d84) Result: Failure Exception: Worker was unable to load function testDb2: 'Error: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail. \\?\D:\home\site\wwwroot\node_modules\ibm_db\build\Release\odbc_bindings.node' Stack: Error: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail. \\?\D:\home\site\wwwroot\node_modules\ibm_db\build\Release\odbc_bindings.node at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18) at Module.load (internal/modules/cjs/loader.js:599:32) at tryModuleLoad (internal/modules/cjs/loader.js:538:12) at Function.Module._load (internal/modules/cjs/loader.js:530:3) at Module.require (internal/modules/cjs/loader.js:637:17) at Module.patchedRequire [as require] (D:\home\site\wwwroot\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46) at require (internal/modules/cjs/helpers.js:22:18) at bindings (D:\home\site\wwwroot\node_modules\bindings\bindings.js:112:48) at Object.<anonymous> (D:\home\site\wwwroot\node_modules\ibm_db\lib\odbc.js:31:31) at Module._compile (internal/modules/cjs/loader.js:689:30)

This works when executing locally from VSCode. From what I can tell, there is no way to get this working from my side as the node worker only supports versions of Node with LTS. That being said I would like to fix this issue as I need to create an Azure Function that connects to a DB2 database. 

#### Investigative information

Please provide the following:

- Timestamp: Any Time (reproduceable)
- Function App name: TestNodeJsKrl
- Function name(s) (as appropriate): TestDb2
- Invocation ID: c18020f5-ddd4-46e1-9ff8-044bd8222d84
- Region: East US 2

#### Repro steps

Provide the steps required to reproduce the problem:
I created a Function App on VSCode using the F1 command. here is the code for each individual file that matters:
<details>
<summary>index.js</summary>

```javascript
const ibmdb = require('ibm_db');
const db2ConnectionString = process.env['DB2_CONNECTION'];

module.exports = function (context) {
    console.log('Beginning!');
    context.log('Beginning context!');
    try {
        let options = {
            connectTimeout: 20
        }
        console.log('Opening connection...');
        let conn = ibmdb.openSync(db2ConnectionString, options);
        console.log('Connection opened!');

        context.res = {
            status: 200,
            body: {
                message: "Connected!",
                result: conn
            }
        };

        context.done();
    } catch (ex) {
        console.log('Exception! ' + ex);

        context.res = {
            status: 500,
            body: {
                message: "Exception! " + ex
            }
        };

        context.done();
    }
};
```

</details>
<details>
<summary>function.json</summary>

```json
{
  "disabled": false,
  "scriptFile": "./index.js",
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [ "GET" ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}
```

</details>
<details>
<summary>package.json</summary>

```json
{
  "name": "nodejs-function",
  "version": "1.0.0",
  "description": "",
  "main": "handler.js",
  "keywords": [
    "azure",
    "functions"
  ],
  "scripts": {
    "test": "echo \"No tests yet...\""
  },
  "dependencies": {
    "64": "^0.2.0",
    "ibm_db": "2.6.1"
  },
  "devDependencies": {}
}
```

</details>
<details>
<summary>local.settings.json</summary>

```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "",
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "DB2_CONNECTION": "DRIVER={DB2};DATABASE=database.xyz.com;UID=db2inst1;PWD=pass;HOSTNAME=8.8.8.8;port=50000"  //Connect to a nonexistent database just to test the module.
  },

  "ConnectionStrings": {},
  "Host": {
    "CORS": "*"
  }
}
```

</details>
One other thing is that you have to use the workaround to get a x64 bit version of node detailed here: /issues/158

#### Troubleshooting steps
I have tried bringing along my own version of node. The most recent one I tried was 12.9.1 and the error I started receiving is that the worker doesn't support versions of Node that don't have LTS. 

I have also tried deploying with the AZ CLI using --build-native-deps as well as trying --remote build.

Both of these deployments succeed, but function execution does not work.

#### Expected behavior

Provide a description of the expected behavior.
The expected behavior should be a timeout from attempting to connect to a nonexistent database.

#### Actual behavior

Instead we get an error saying that the side-by-side configuration is incorrect and its referencing the ODBC driver.

#### Known workarounds

No known workarounds at the moment besides using a Linux System.

#### Related information 

I am using a Windows NodeJs Function App, unfortunately with my current set-up I need to stick with Windows for now.

**Comment by mhoeger** [comment]
@kyallanum - sorry for the delayed response. My understanding of this issue is that:
 - If Windows, ibm_db module only works with Node.js 12
 - If Linux, ibm_db module will work for Node.js 8+?

And when you say you have it running locally, is it through the Azure Functions extension (or Azure Functions CLI, `func start`)? Or is it through running your code directly from a node process?

**Comment by kyallanum** [comment]
Hello @mhoeger its okay! 
So I've been told that Linux works with the ibm_db module, I don't know what version of Node.js.

With Windows, any version seems to work locally (by pressing the F5 Key in my VSCode (which has Azure Functions Extension). Running it on an Azure Function gives it the above error with every version I've tried (which is any LTS version), with "side-by-side configuration is incorrect" error.

I have tried deploying both with VSCode and with the command func azure functionapp publish <functionappname> --build remote and with the --build-native-deps flag. All three methods do not work and produce the same result.

**Comment by mhoeger** [comment]
@kyallanum - thanks for the details! Sorry one more bit to clarify, so locally, you have your host.json and function.json's and everything, and that seems to work. But when you deploy it, and it's "running on an Azure Function", so running it on the cloud/Azure, it starts throwing that error?

If that's the case, how are you deploying your function app? And can you share your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)?

**Comment by mhoeger** [comment]
And my two theories are this:
When you ran `npm install`, something about your local environment may be different than your deployed version (major version of node, for example). One thing that you can do, is not deploy your node_modules and install them on the deployed version.

You can do this through [Kudu](https://david-obrien.net/2016/07/azure-functions-kudu/) or in the Azure Portal through the "Console", which shows up next to the streamed logs:
<img width="891" alt="Screen Shot 2019-10-09 at 4 22 53 PM" src="https://user-images.githubusercontent.com/8888531/66527483-3a50de00-eab1-11e9-820d-a2e2f4c950d2.png">
^ note that this is a c# function, but same thing for JS :) and you can just navigate to the root (wwwroot) and run an npm install there. Or from wherever you have your package.json

My second theory is, if this doesn't work, then you may be running into sandbox restrictions. Azure Functions run in a sandboxed environment, which restricts access to shared components like the registry, cryptography, and graphics subsystems (see [doc here](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#general-sandbox-restrictions) for more). If the module is doing anything low-level, it may be related.

My money's on theory number one, but let me know if it doesn't work or you run into issues

**Comment by kyallanum** [comment]
Taking out of idle. I will get back to this as soon as I can.
