### ISSUE TITLE
Warning I need to use LTS when I am using LTS 12

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-nodejs-worker#256]
I get the following warning (locally) when trying to use node 12:

```
[11/2/2019 12:18:03 AM] [error] Incompatible Node.js version. The version you are using is v12.13.0, but the runtime requires an LTS-covered major version (ex: 8.11.1 or 10.14.1). LTS-covered versions have an even major version number (8.x, 10.x, etc.) as per https://github.com/nodejs/Release#release-plan. For deployed code, change WEBSITE_NODE_DEFAULT_VERSION in App Settings. Locally, install or switch to a supported node version (make sure to quit and restart your code editor to pick up the changes).
```

Node 12.13.0 is the latest LTS release, so I wouldn't expect to be told to use an LTS release.

#### Investigative information

Please provide the following:

N/A - repros locally with node 12.13.0 installed

Func host version:

```
Azure Functions Core Tools (2.7.1724 Commit hash: faf97bb64a53fbf1c7ef7e5c608c392c8662951b)
Function Runtime Version: 2.0.12763.0
```

#### Repro steps

Provide the steps required to reproduce the problem:

install node 12.13.0 (latest node LTS - Erbium)
run `func host start`

#### Expected behavior

Provide a description of the expected behavior.
(
It should work with the LTS version

AND

Fetch the list of known good LTS from a public source (such as GitHub releases) before yelling
)
OR

If the list is going to be hard coded into the JS worker, you should say which specific versions are supported, not mention LTS at all.

#### Actual behavior

Provide a description of the actual behavior observed.

yells at me for using an LTS version (that it presumably doesn't recognize)

#### Known workarounds

Provide a description of any known workarounds.

N/A

#### Related information 

Provide any related information 
N/A

**Comment by brettsam** [comment]
@mhoeger

**Comment by anthonychu** [comment]
@mhoeger Could we do something like this instead if this is running in Core Tools? If Core Tools and the installed Node version is not officially supported but is >= the minimum supported version, print a warning but allow still worker to start.

**Comment by mhoeger** [comment]
The behavior Chris described is what we do now for Node.js 12- do you think this should be the behavior for everything including Node.js 11, 13 and 15?

https://github.com/Azure/azure-functions-nodejs-worker/blob/67941a159bf893b9459fd9a9bbdd691f8ba10838/src/nodejsWorker.ts#L27

**Comment by mhoeger** [comment]
And if yes, yeah we could make that change!

**Comment by anthonychu** [comment]
I think that warning is gone on the v2.x branch. What I was thinking of was this:

https://github.com/Azure/azure-functions-nodejs-worker/blob/8dcd914ce2a053595e6a038475de53b7800c507e/src/nodejsWorker.ts#L31-L34

It should continue to throw in production if not running on a supported LTS version. But if running in Core Tools, perhaps it should only print a warning and continue, as long as they're using Node 8 or higher. That way folks who use Current don't have to switch to develop for Functions, but they are warned that it's not a supported version.

**Comment by anthonychu** [comment]
A quick update on this thread.

@mhoeger @alrod I think you looked into this and supporting more versions requires the worker to package more gRPC binaries. So based on this, we decided to park this item.

However, going through some user research right now (folks running functions in Static Web Apps), folks are installing node via stuff like homebrew, which defaults to latest current, and once they do that it's really hard to dig out of that hole. I wonder if we can support the latest current version when running locally. So currently, this means supporting Node 15 with a warning (but we can ignore the previous current versions).

**Comment by mhoeger** [comment]
Closing as the original issue has been addressed and the update on allowing "current" versions during local dev is tracked here: https://github.com/Azure/azure-functions-nodejs-worker/issues/363
