### ISSUE TITLE
Functions Host V3 and Nodej.s Worker V2

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#260]
v2.x branch currently (see changes [here](https://github.com/Azure/azure-functions-nodejs-worker/compare/v2.x?expand=1)):
- introduces "v1WorkerBehavior" flag which reverts everything "[breaking]"
    - _In the future: we want to have the functions host send over specific breaks to opt out of_
- [breaking] throws on Node.js v8, keeps 8 binaries for V2 host compat
- changes worker version to 2.0.0
- [breaking] does not duplicate http payload in `context.bindingData`
- [breaking] fixes #228 (handles http output correctly on context.(null, { body: "hello" });
  - TODO: https://github.com/Azure/azure-functions-nodejs-worker/issues/268
- [breaking] fix camelCase of timer trigger object: #188 
- [breaking] fix type conversion of code like `return { outputBinding: info, outputBinding2: info };`: https://github.com/Azure/azure-functions-nodejs-worker/issues/232
- [breaking] consume "TypedDataCollection" https://github.com/Azure/azure-functions-nodejs-worker/issues/262
- add unspecified for http => https://github.com/Azure/azure-functions-host/issues/4890#event-2852029079

TODO:
~- remove Node.js v10 support?~
- [breaking] in host and worker, make sure http payload "as raw" as possible
- [breaking] `rawBody` http property should not be a UTF-8 string for byte data (Azure/azure-functions-host#4475)

In the future:
- explore options for bugs with protobuf.js and windows (Issue 1303, Issue 1275)
    - protoc or just default Linux and accept Windows bugs? Probably document windows bugs
- do correct fix for camelCase #188 (potentially add .proto)

**Comment by ColbyTresness** [comment]
Also note we need a change on the platform to auto upgrade customers node versions if they move to V3 and are on an older Node version (8, for instance). They should be notified of this change.

**Comment by mhoeger** [comment]
Closed with https://github.com/Azure/azure-functions-host/pull/5335
