### ISSUE TITLE
Improve default of toTypedData method (converting protobuf messages => JavaScript)

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#267]
Issue raised in this PR: https://github.com/Azure/azure-functions-nodejs-worker/pull/263
> What will happen in case the type is not defined in these if, specially there is no else default case? This case should not ever happen.

We should change the default to something more helpful than doing nothing

**Comment by ejizba** [comment]
Addressed by https://github.com/Azure/azure-functions-nodejs-library/commit/efa5fb369c1315fe7c7352cadf2bb9dfe2f31358
