### ISSUE TITLE
ServiceBus output binding, duplicate detection not working

### ISSUE THREAD

**Issue by bradoyler** [Azure/azure-functions-nodejs-worker#293]
When using an output binding like:
```
 {
      "name": "myEvent",
      "type": "serviceBus",
      "queueName": "my-events",
      "connection": "my-servicebus",
      "direction": "out"
 }
```

I have tried setting the messageId (as below) and the dup detection on the sb queue never seems to work.
```
context.bindings.myEvent = { messageId: '123', foo: 'bar' } 
```
Only way I could get dup detection working is to use the `@azure/service-bus` client.

Is 'duplicate detection' a supported feature of the `serviceBus` output binding? I can't seem to find the messageId referenced in any example or this repo. 

I'd appreciate the help, thanks.

**Comment by v-anvari** [comment]
Tagging @alrod , for more insights

**Comment by pvpetrac** [comment]
Any changes there? I'd like to be able to customize applicationProperties too.. the only customizable thing is apparently message body

**Comment by alrod** [comment]
Specifying `messageId `is not supported by ServiceBus output biding in javasript. You can assign a string, a byte array, or a JavaScript object:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-output?tabs=javascript#usage

**Comment by floriankoch** [comment]
@alrod   any plans to support this in the future?

**Comment by jensbarthel** [comment]
This effectively renders service bus duplicate detection, which is one of its selling points, useless for azure function outputs. Are there any plans to address this in the future?
