### ISSUE TITLE
TypeError: context.log.warn is not a function

### ISSUE THREAD

**Issue by rukasakurai** [Azure/azure-functions-nodejs-worker#295]
#### Repro steps
1. For ah httpTrigger Azure Function written in TypeScript
2. Add `context.log.warn("xxx");` to the code
3. Run a unit test on the function using [jest](https://jestjs.io/)

#### Expected behavior
The expected behavior is that the unit test passes.

#### Actual behavior
`TypeError: context.log.warn is not a function`

**Comment by rukasakurai** [comment]
Here's some sample code that reproduces the error when running `npm test` to execute the jest unit tests on the code:
https://github.com/rukasakurai/azure-functions-httptrigger-typescript-sample

**Comment by mhoeger** [comment]
Hi @rukasakurai, it looks like your original issue is resolved but I can keep this issue open to track better support for unit tests? Please note though that we likely won't publish those as there are many different testing frameworks and will rely on other folks to contribute (example: https://www.npmjs.com/package/azure-function-context-mock)

**Comment by ThaddeusJiang** [comment]
Hi @rukasakurai  @mhoeger 

It works.

```
const context = {
  log: jest.fn(),
}

context.log.warn = jest.fn();
```

**Comment by ejizba** [comment]
Closing in favor of https://github.com/Azure/azure-functions-nodejs-worker/issues/515 and https://github.com/Azure/azure-functions-nodejs-worker/issues/120
