### ISSUE TITLE
No w3c correlation headers in app insights on outgoing requests

### ISSUE THREAD

**Issue by hannesne** [Azure/azure-functions-nodejs-worker#297]
When using the app insights Nodejs sdk in a node app, it adds the following headers: 

`
        "request-context": "appId=cid-v1:957b1ee6-64f0-4ac7-9562-44044ba525c6",
        "request-id": "|87114b1459694205a84de2d5b078cbdd.dd94903cc8a44eaa.",
        "traceparent": "00-87114b1459694205a84de2d5b078cbdd-dd94903cc8a44eaa-01",
        "x-ms-request-id": "87114b1459694205a84de2d5b078cbdd",
        "x-ms-request-root-id": "|87114b1459694205a84de2d5b078cbdd.dd94903cc8a44eaa.",
`
In an Azure Functions app, only the request-context seems to be added, despite calling `.setDistributedTracingMode(AppInsights.DistributedTracingModes.AI_AND_W3C) ` when configuring the sdk.
Distributed tracing mode is also set in the host.json, and doesn't seem to have an effect.

The code for the Azure Function is as follows: 

```typescript
import { AzureFunction, Context, HttpRequest } from "@azure/functions";
const AppInsights = require('applicationinsights');
import Axios, { } from 'axios';

AppInsights
    .setup()
    .setDistributedTracingMode(AppInsights.DistributedTracingModes.AI_AND_W3C)
    .setAutoDependencyCorrelation(true)
    .setAutoCollectRequests(true)
    .setAutoCollectPerformance(true)
    .setAutoCollectDependencies(true)
    .setAutoCollectExceptions(true)
    .setAutoCollectConsole(true)
    .setUseDiskRetryCaching(true)
    .setSendLiveMetrics(true)
    .start();

const httpTrigger: AzureFunction = async function (context: Context): Promise<void> {
   
    context.log('HTTP trigger function processed a request.');
    AppInsights.getCorrelationContext(); //this is null, but should probably not be.
    const response = await Axios.get('https://postman-echo.com/get');

    context.res = {
        body: response.data,
        headers: {
            'Content-Type': 'application/json'
        },
        status: response.status
    }
};

export default httpTrigger;
```

This is using func version 3.0.2245

This seems to be related to https://github.com/Azure/azure-functions-host/issues/5901

**Comment by ejizba** [comment]
Hi @hannesne sorry for the delay. It looks like this was addressed in https://github.com/microsoft/ApplicationInsights-node.js/issues/585 by adding these docs here: https://github.com/microsoft/ApplicationInsights-node.js#azure-functions
