### ISSUE TITLE
Upgrade to use grpc-js

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#312]
https://grpc.io/blog/grpc-js-1.0/

Should I use @grpc/grpc-js or grpc?
> The original Node gRPC library (grpc) will no longer receive feature updates and we plan to deprecate it in a year, so we recommend that you use gRPC-JS, @grpc/grpc-js.
> However, some advanced features haven’t been ported to gRPC-JS yet, such as full compression support or support for other load balancing policies. If you need one of these features, you should use the grpc library, but open a feature request over gRPC-JS to let us know which features you are missing the most.

**Comment by ejizba** [comment]
Fixed in https://github.com/Azure/azure-functions-nodejs-worker/pull/417
