### ISSUE TITLE
Remove "sys" from trigger data from host => language worker

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#317]
Currently, we pass data like "sys" (and for HTTP, "query" and "headers". However values in "sys" in particular are not RPC-friendly and we should avoid passing those values if we can.

Node.js worker is the only worker that we manage that exposes these values to end-users.

**Comment by pragnagopa** [comment]
Transferred issue here. If possible please assign it to next sprint. Thanks!

**Comment by mathewc** [comment]
Yes, for this change, we should add query/headers from the request body sent. Then we'll be able to reapply my http extension changes to omit these from the payload. As you mention, we'll also remove the "sys" node.

**Comment by mhoeger** [comment]
hey @mathewc - sorry I missed your note there! :( 
Here's the issue tracking the change to our protobuf contract: https://github.com/Azure/azure-functions-language-worker-protobuf/issues/49
and this is tracking the node worker changes:
https://github.com/Azure/azure-functions-nodejs-worker/issues/324

These both will let us remove "query" and "headers" from trigger metadata that gets passed over
