### ISSUE TITLE
Move dev => v1.x and v2.x => dev

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#331]
Active development on worker v2.x

**Comment by pragnagopa** [comment]
Moving to next sprint. Please move it triaged if there are higher priority work items.

**Comment by mhoeger** [comment]
Note: moved dev => v1.x and changed default branch to v2.x - dev staying as is

**Comment by pragnagopa** [comment]
Can you please open an issue to track renaming master to `main` ?
