### ISSUE TITLE
Enable new Node.js placeholder templates

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#333]
Tracking item for Antares work

Related:
https://github.com/Azure/azure-functions-host/issues/6583

**Comment by fabiocav** [comment]
Is this done? Can we close this issue?

**Comment by mhoeger** [comment]
Change needs to happen before 10/6 but is not in yet.

**Comment by mhoeger** [comment]
Change made in Antares
