### ISSUE TITLE
CA work

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#334]
Tracking item for platform work

**Comment by mhoeger** [comment]
Did not get a chance to work on this (and need Suwat's help) - bumping sprint

**Comment by pragnagopa** [comment]
@mhoeger - please update if any progress has been made for this item.

**Comment by mhoeger** [comment]
Unfortunately, didn't get much time to invest in this item (on servicing first half of sprint) - will be syncing up with Suwat for latest

**Comment by fabiocav** [comment]
Moving to sprint 89

**Comment by fabiocav** [comment]
@mhoeger FYI, moving this back to `triaged`

**Comment by ejizba** [comment]
Closing this issue as it doesn't actually have any information
