### ISSUE TITLE
Typings for Bindings

### ISSUE THREAD

**Issue by ntziolis** [Azure/azure-functions-nodejs-worker#345]
Right now there are only bindings for a general context. Accessing input / output bindings is not typesafe:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=javascript

```
context.bindings.myBlob
```

Instead it should be possible to provide a generic argument to the Context interface that holds a typed version of the bindings

```
const typedContext : Context<{
   myBlob: BlobTriggerIn
}>
```

Without these typings the typescript story of azure functions is incomplete.

**Comment by ejizba** [comment]
We have improved these in the new programming model. Any further suggestions should be filed in this repo: https://github.com/Azure/azure-functions-nodejs-library
