### ISSUE TITLE
LTS Node version (14.15.0) is not supported.

### ISSUE THREAD

**Issue by kbarnes3** [Azure/azure-functions-nodejs-worker#346]
When trying to use a Node based Azure Function, I get the following error:

```
node_modules\azure-functions-core-tools\bin\workers\node\dist\src\nodejsWorker.js:35
[2020-11-06T23:29:08.189]         throw message;
[2020-11-06T23:29:08.191]         ^
[2020-11-06T23:29:08.192] Incompatible Node.js version (v14.15.0). Refer to our documentation to see the Node.js versions supported by each version of Azure Functions: https://aka.ms/functions-node-versions
```

I find this error message clear and the documentation also looks consistent. However, v14.15.0 is the current LTS version offered on nodejs.org and it is somewhat difficult to find a compatible version on that site. Is there an ETA for support for version 14.* of Node?

#### Investigative information

```
func --version
3.0.2931
```

**Comment by anthonychu** [comment]
@kbarnes3  This should be unblocked locally in Azure Functions Core Tools 3.0.2996. You'll be able to run function apps on Node 14 in Azure soon.

**Comment by kbarnes3** [comment]
Thanks @anthonychu, I updated my core tools and now I'm able to use Node 14 locally.
