### ISSUE TITLE
Automatically decode x-www-form-urlencoded and multipart/form-data HTTP request bodies

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-nodejs-worker#347]
Make it easy to parse data posted directly from HTML forms to an HTTP triggered function. This may be particularly useful for Azure Static Web Apps but in general this comes up regularly for Functions.

Examples from recent blog posts:
* @svdoever https://www.sergevandenoever.nl/Processing-multipart-form-data-in-nodejs-azure-function-with-httptrigger/
* @estruyf https://www.eliostruyf.com/parse-multipart-form-data-azure-function/

```html
<h1>x-www-form-urlencoded</h1>
<form action="http://localhost:7071/api/HttpTrigger1" method="POST">
  <div>
    Name: <input name="name" value="Azure Functions" />
  </div>
  <div>
    Greeting: <input name="greeting" value="Hello" />
  </div>
  <div>
    <input type="submit" value="Submit" />
  </div>
</form>
```

```html
<h1>multipart/form-data</h1>
<form action="http://localhost:7071/api/HttpTrigger1" method="POST" enctype="multipart/form-data">
  <div>
    Name: <input name="name" value="Azure Functions" />
  </div>
  <div>
    Greeting: <input name="greeting" value="Hello" />
  </div>
  <div>
    <input type="file" name="myfile">
  </div>
  <div>
    <input type="submit" value="Submit" />
  </div>
</form>
```

Thinking something like:

```js
module.exports = async function (context, req) {
    const form = req.formPostData();
    const { name, greeting, myfile } = form;

    // myfile:
    // {
    //     "content-type": "image/jpeg",
    //     "data": <buffer>
    // }

    const fileContentBuffer = myfile.data;
    context.log(`name: ${name} - greeting: ${greeting}`);
    context.log(`filename: ${myfile.filename} - content type: ${myfile['content-type']} - bytes: ${fileContentBuffer.length}`);
    context.res = {
        status: 302,
        headers: {
            "location": "https://microsoft.com/thankyou.html"
        }
    };
}
```

Related: #146 

/cc @mhoeger @johnpapa @craigshoemaker @burkeholland

**Comment by shammelburg** [comment]
This would be amazing

**Comment by anthonychu** [comment]
Needs further discussion. Perhaps we can ship a separate library (or in `@azure/functions`)?

**Comment by estruyf** [comment]
This would be great!

**Comment by adrwh** [comment]
Any chance native support to parse x-www-form-urlencoded has been added yet to Azure Functions?
My use case is static apps with API function.

**Comment by ejizba** [comment]
I've just about got this working and wanted to post here in case anyone had feedback on the API. cc @anthonychu in particular

```typescript
export interface HttpRequest {
    // ...

    parseFormBody(): Promise<Form>;
}

export interface Form extends Iterable<[string, FormPart]> {
    /**
     * Returns the value of the first name-value pair whose name is `name`. If there are no such pairs, `null` is returned.
     */
    get(name: string): FormPart | null;

    /**
     * Returns the values of all name-value pairs whose name is `name`. If there are no such pairs, an empty array is returned.
     */
    getAll(name: string): FormPart[];

    /**
     * Returns `true` if there is at least one name-value pair whose name is `name`.
     */
    has(name: string): boolean;
}

export interface FormPart {
    value: Buffer;
    fileName?: string;
    contentType?: string;
}
```

A few notes:

- My preference is to add a method to the request object similar to Anthony's example (I don't think there's much value to putting this in a separate library).
- I chose to model the `Form` interface after Node.js's built-in `URLSearchParams` [class](https://nodejs.org/api/url.html#class-urlsearchparams). It's a bit more complicated than Anthony's simple object example because forms are allowed to have multiple parts with the same name. However, I like it because most people will probably only have one part per name and will just do a `get`.
- I think it makes sense to use the same exact API for both "x-www-form-urlencoded" and "multipart/form-data"
- I debated using the `string` type in a few places for parts that aren't files (as opposed to `Buffer` or even `FormPart`), but ultimately decided consistency was best.

**Comment by anthonychu** [comment]
Love it. Thanks for taking the multiple values into account.

**Comment by sinedied** [comment]
@anthonychu @ejizba It seems that this is only for v3 runtime and not available in v4 😞  Any chance it will also come to v4 or was there a reason to get it removed?

**Comment by anthonychu** [comment]
@sinedied This change is in v3.2.0 and above of the Node.js worker. It's a bit confusing but Azure Functions v4 uses the v3 Node.js worker, and v3 uses v2. 😆

You can see that here:
- https://github.com/Azure/azure-functions-host/blob/v3.x/src/WebJobs.Script/WebJobs.Script.csproj#L58
- https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/WebJobs.Script.csproj#L59

This is the commit that upgraded the host to 3.2.0: https://github.com/Azure/azure-functions-host/commit/07d88f9b875e154326e8a301c52fbfca2aea2f3d At the top of the commit, you can see it's in v4.3.0 of the host. I think that version hasn't been rolled out yet. Maybe @ejizba can help provide an ETA.

**Comment by ejizba** [comment]
Yes Anthony is correct, you will need v4.3.0 of the _host_ or higher (which includes v3.2.0 of the _node.js worker_). You can check the releases of the host in either one of these places:
- https://github.com/Azure/azure-functions-host/releases
- https://github.com/Azure/app-service-announcements/issues

The 4.3.0 release started a while ago, but unfortunately had a few issues requiring them to do a 4.3.1 and 4.3.2 release. Hopefully 4.3.2 will roll out completely in the next few weeks, but honestly the host release cycle is a bit hard to predict and I'm not an expert on that.
