### ISSUE TITLE
Document how to pass command line options for Node.js

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#348]
The way to do it is with environment variable / app setting: languageWorkers__node__arguments

Example:
```
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "AzureWebJobsStorage": "",
    "languageWorkers__node__arguments": "--prof"
  }
}
```

Add section [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=v2#local-debugging)

**Comment by anthonychu** [comment]
@pragnagopa Can you share a bit more info on what needs to be done if we were to do this in production? I don't know if folks should be doing profiling in prod, but perhaps for configuring other arguments like this: https://github.com/Azure/azure-functions-host/issues/6550

**Comment by pragnagopa** [comment]
Above instructions are OK for non-consumption skus . 

In Consumption, we should call out the following in the docs:


If your app is using consumption plan, you need  to add following appsetting. **Note: This will increase cold starts for your functions**

**App setting key WEBSITE_USE_PLACEHOLDER with value set to 0**

**Comment by mhoeger** [comment]
This will be improved after: https://github.com/Azure/azure-functions-host/issues/7139
We should document the minor perf impact

**Comment by ejizba** [comment]
This exists in the docs now: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=v2-v3-v4-export%2Cv2-v3-v4-done%2Cv2%2Cv2-log-custom-telemetry%2Cv2-accessing-request-and-response%2Cwindows-setting-the-node-version#local-debugging
