### ISSUE TITLE
Require Global Variable

### ISSUE THREAD

**Issue by nsd-david** [Azure/azure-functions-nodejs-worker#360]
#### Investigative information

Please provide the following:

- Timestamp:2020-12-24T00:27:24.318Z
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:96e59651-920e-44dc-b6af-c9aa2bd8c594
- Region:US-East

#### Repro steps

Provide the steps required to reproduce the problem:

Here's my function.json
```
{
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "route": "email",
      "methods": [
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}
```

My function looks like this (I modified it, so it's easier to read)
```
var inversify = require('inversify');
const EmailService = require('../services/EmailService');

module.exports = async (req, context) => {
  inversify.decorate(inversify.injectable(), EmailService);
  const container = new inversify.Container();
  container.bind('emailService').to(EmailService).inSingletonScope();

  context.res = {
    status: 200,
    body: 'body'
  };
  context.done();
};
```

When I run this function locally everything works well the first time I call POST /email, but when I call POST /email again it always fails with an inversify error that lets me know that I can't call decorate multiple times.

The error happens on `inversify.decorate(inversify.injectable(), EmailService);` because `var inversify = require('inversify');` is only called once after starting the function, but `inversify.decorate(inversify.injectable(), EmailService);` gets called each time I call POST /email.

How can I prevent this from happening? context.done() doesn't help. I also tried moving `var inversify = require('inversify');` inside the module.exports function.

#### Expected behavior

Provide a description of the expected behavior.

`var inversify = require('inversify');` should be called each time after context.done(); or adding `var inversify = require('inversify');` in the module.exports function should prevent the function from remembering the first initialization of inversify.

#### Actual behavior

Provide a description of the actual behavior observed.

`var inversify = require('inversify');` only gets called once, and `inversify.decorate(inversify.injectable(), EmailService);` gets called each time I run the function which causes an error

#### Known workarounds

Provide a description of any known workarounds.

I'm able to fix the issue by calling inversify.decorate outside module.exports. I don't like that solution since even though it seems to work locally, I'm not sure if it will once in production when many users call POST /email at the same time.
```
var inversify = require('inversify');
const EmailService = require('../services/EmailService');

inversify.decorate(inversify.injectable(), EmailService);

module.exports = async (req, context) => {
  const container = new inversify.Container();
  container.bind('emailService').to(EmailService).inSingletonScope();

  context.res = {
    status: 200,
    body: 'body'
  };
  context.done();
};
```

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by anthonychu** [comment]
@nsd-david Yes what you have there should work. At startup, the Node worker requires/imports each function module and the initialization code outside the function body runs once and this is cached by Node. I don't believe the worker does anything to the require cache that can cause things to be reimported, but @mhoeger can confirm.

As you've noticed, the exported function itself will be run on every invocation. I don't know enough about inversify but it feels like these lines should be outside the function as well so they are only called once:

```js
const container = new inversify.Container();
container.bind('emailService').to(EmailService).inSingletonScope();
```

What you also have to be careful about is if you have more than one function in your app and you need to set up inversify in multiple functions. I would recommend that you put all the code that need to run once at startup into its own module and require it from all functions files that need it, so that that code is in one place and executed once. I also think the container setup code should be in there as well, and the module should export the container. Each place that you need a service from inversify, you probably should use the exported container.

Another small thing to point out is that you don't need to call context.done() if your function is async (returns a promise). context.done() is required for functions that aren't async, and can cause issues in async functions.

**Comment by nsd-david** [comment]
@anthonychu I'll remove `context.done()` from my async functions. The reason I can't move 

```
const container = new inversify.Container();
container.bind('emailService').to(EmailService).inSingletonScope();
```

outside is because I need req in some cases
for example
```
const container = new inversify.Container();
container.bind('emailService').toDynamic(new EmailService(req.query.param)).inSingletonScope();
```

In order to re-use inversify in all my functions I created a wrapper function

startup contains the inversify code, and I just re-use it in all functions
```
const startup = (func) => {
   // inversify code
   return func;
}
```

function 1
```
const startup = require('../startup');
module.exports = startup(async (req, context) => {
  // function code
})
```

function 2
```
const startup = require('../startup');
module.exports = startup(async (req, context) => {
  // function code
})
```

Do you see any issues with doing that?

**Comment by mhoeger** [comment]
+1 to what @anthonychu has said!

I think rather than doing the above, you're going to want to just setup the "inversify" object once.

Example (sorry for not great names):

inversifyInstance.js
```javascript
const inversify = require('inversify');
const EmailService = require('../services/EmailService');
inversify.decorate(inversify.injectable(), EmailService);

module.exports = inversify;
```
Any index.js
```javascript
const inversifyInstance = require('./inversifyInstance');
module.exports = async (req, context) => {
  const container = new inversifyInstance.Container();
  container.bind('emailService').to(EmailService).inSingletonScope();

  context.res = {
    status: 200,
    body: 'body'
  };
};
```

**Comment by nsd-david** [comment]
@mhoeger @anthonychu thank you for helping me with this. You're both going way above and beyond what I was expecting for help.

The reason I can't just create inversifyInstance.js is because my inversify instance depends on variables from **req**.

What I'm doing right now, and it seems to be working locally (I haven't tested remote yet) is using a higher order function

Any index.js
```
const startup = require('../startup');

// I add as many services as I need here
const main = async (emailService, ...) => {
  emailService.sendEmail(from, to, body);

  context.res = {
    status: 200,
    body: 'body'
  };
};

module.exports = startup(main);
```

startup.js
```
const inversify = require('inversify');
const EmailService = require('../services/EmailService');

const startup = (mainFunc) => {
  return async (context, req) => {
    const container = new inversify.Container();
    container.bind('emailService').toDynamicValue(() => new EmailService(req.query.paramSentInRequest)).inSingletonScope();

    // get a list of function parameters (emailService in this example)
    const funcParams = getFuncParams(mainFunc);

    // loop through all function parameters and call container.get for each one, so now requestedServices has an instance of EmailService
    const requestedServices = createRequestedServices(container, funcParams);

     // inject all created instances into original function
    await mainFunc(...requestedServices);
  }
}
```

**Comment by mhoeger** [comment]
@nsd-david - I believe that will work! If it all works as expected locally, then there shouldn't be any difference when deployed (each Functions instance is its own Node.js process, where each Functions instance can can process multiple Function invocations in parallel. Locally, you see what happens with just one Functions instance/one Node.js process)

**Comment by nsd-david** [comment]
@mhoeger okay that makes sense. I feel better about pushing these changes to our remote functions. Thanks again for your help.
