### ISSUE TITLE
Improve local dev experience for unsupported versions of Node.js

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#363]
It's a better local development experience if warnings are issued on local development rather than outright failure for missing Node.js versions

**Comment by mhoeger** [comment]
This is a bigger item than expected - for local we also need to bundle native dependencies as done [here](https://github.com/Azure/azure-functions-nodejs-worker/blob/aa967888f5d7e983e8aa2889863bf5031975a752/package.ps1#L28)

For package size, we don't want to include these to our deployed versions on Azure

cc: @alrod

**Comment by anthonychu** [comment]
Maybe allowing a version that's not supported in Azure could cause problems. Let's not do this for now.

**Comment by mhoeger** [comment]
Per Anthony's comment here: https://github.com/Azure/azure-functions-nodejs-worker/issues/256#issuecomment-802998063

_@mhoeger @alrod I think you looked into this and supporting more versions requires the worker to package more gRPC binaries. So based on this, we decided to park this item._

_However, going through some user research right now (folks running functions in Static Web Apps), folks are installing node via stuff like homebrew, which defaults to latest current, and once they do that it's really hard to dig out of that hole. I wonder if we can support the latest current version when running locally. So currently, this means supporting Node 15 with a warning (but we can ignore the previous current versions)._
