### ISSUE TITLE
Any thoughts on upgrade our TypeScript version?

### ISSUE THREAD

**Issue by davidmrdavid** [Azure/azure-functions-nodejs-worker#365]
As per our [package.json](https://github.com/Azure/azure-functions-nodejs-worker/blob/v2.x/package.json#L29), we are currently pinned to TypeScript version  `2.x`. This prevents us from having neat tools like a [linter rule](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md) that would warn us of _suspicious_ if-statements on `falsy` values. Something like this would have helped us prevent [this](https://github.com/Azure/azure-functions-durable-js/issues/50) error which is caused by [this](https://github.com/Azure/azure-functions-nodejs-worker/blob/4247c6b39d7b48720b5f36dbcb4ce42461360b4a/src/WorkerChannel.ts#L233) line 😄 .

Wondering if there's a known reason why we haven't made the upgrade or if its just a matter or upgrading and fixing the expected type mismatches that would now show up? If its the latter, I'd be happy to help make the upgrade as it would probably be a positive change across the board. Please let me know your thoughts!

_Thanks!_

cc/ @mhoeger

**Comment by mhoeger** [comment]
Note: upgrade to "any" types like `bindings` and `bindingData` on context to "unknown" https://github.com/Azure/azure-functions-nodejs-worker/pull/359#issuecomment-767147393
