### ISSUE TITLE
Support 'this' parameter in user functions

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-functions-nodejs-worker#37]
https://github.com/Azure/azure-webjobs-sdk-script/issues/1702

**Comment by mamaso** [comment]
https://github.com/Azure/azure-webjobs-sdk-script/pull/1707

**Comment by christopheranderson** [comment]
This would enable a sample that looks like this:

```javascript
class MyObj {
    constructor(){this.foo=1};
    increment(context) { this.foo++; context.done(); }
}

const myObj = new MyObj()
module.exports = myObj
```
where entry point was set to a method on the `myObj` named "increment"

Today, if you do this, it will use a global foo, not the MyObj context. This isn't a good experience.
