### ISSUE TITLE
Add a detector for Linux apps that have WEBSITE_NODE_DEFAULT_VERSION set

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-nodejs-worker#378]
Helps identify situations where customers are trying to change the Node.js version on Linux by using the app setting.

**Comment by hossam-nasr** [comment]
Created a work item [here](https://dev.azure.com/Azure-Functions-Supportability/IPD%20Reduction%20-%20Nickel/_boards/board/t/IPD%20Reduction%20-%20Nickel%20Team/Feature%20Areas/?workitem=612) to track this on the detectors board. 

/cc @stefanushinardi

**Comment by ejizba** [comment]
This was fixed a while ago 

![Screenshot 2023-05-23 at 5 41 24 PM](https://github.com/Azure/azure-functions-nodejs-worker/assets/11282622/8090d790-27cd-47c5-8cf6-86822211e172)
