### ISSUE TITLE
[Question]: New type for context.req.query

### ISSUE THREAD

**Issue by asbjornh** [Azure/azure-functions-nodejs-worker#381]
`@azure/functions` version `1.2.3` has apparently changed the TypeScript type of `context.req.query` from `Record<string, string>` to `Record<string, string | undefined>`.

Basically, I just need to know why this was changed, because this change has created a _ton_ of type errors in our app and I need to find the correct way of fixing them.

I can think of two reasons for this change:
1) Property values in `context.req.query` can be `undefined`. This doesn't seem likely, because I'm not able to reproduce this (using `azure-functions-core-tools@3.0.3388`). No matter what query string I pass all property values in `context.req.query` are strings.
2) The library wants to impose stricter null checks on consumers

Does anyone know which is the case (if any of them)?
Thanks!

**Comment by mhoeger** [comment]
Hi - the query parameter value can be undefined in the following cases:
```
http://localhost:7071/api/HttpTrigger?hello=
http://localhost:7071/api/HttpTrigger?hello
http://localhost:7071/api/HttpTrigger
```

where my code is this:
```javascript
module.exports = async function (context, req) {
    context.log(context.req.query.hello);
};
```

Did I understand your question correctly? Sorry about the inconvenience as well.

**Comment by asbjornh** [comment]
Hi and thanks.
Yeah you got it, and no worries!

For the three URLs you mentioned, I get the following values for `context.req.query` using a function very similar to yours:

- `{ hello: "" }`
- `{ hello: "" }`
- `{}`

In other words, I get empty strings and no `undefined`.

**Comment by mhoeger** [comment]
Ahh sorry - that's expected :) The case of `undefined` then is: `http://localhost:7071/api/HttpTrigger`

One thing you can do, if you know that your client will definitely always send the HTTP query of some name, is this:
```typescript
declare module '@azure/functions' {
    export interface HttpRequestQuery {
      hello: string
    }
}
```

**Comment by asbjornh** [comment]
Unless I'm mistaken, the type `{ [key: string]: string | undefined }` means that the object in question can contain the _literal_ `undefined`: `{ something: "", hello: undefined }`, which is different from `{ something: "" }` if you have any logic that involves iterating over object properties (which we do). To me it still doesn't seem like the `query` object will ever contain `undefined` literals.

From what you're saying, it seems like `undefined` was included in the property type to express the fact that any _specific_ property in `query` might not be defined. Could you confirm or deny? 😊

**Comment by pellebjerkestrand** [comment]
Seems like this is the commit that changed the types: https://github.com/Azure/azure-functions-nodejs-worker/commit/eb2845b31477d7f0b45a2b17de642d154944452c

The PR is at https://github.com/Azure/azure-functions-nodejs-worker/pull/359

I also can't produce any behavior in which the values are `undefined`.

**Comment by pellebjerkestrand** [comment]
The Applications Insights client has the correct type for `headers` (AFAIK `Record<string, string>` and `{ [key: string]: string; }` are the same) in https://github.com/microsoft/ApplicationInsights-node.js/blob/c13a78d900be17f000992c2a2fbfb162062c5271/Library/Functions.ts#L17

Its whole `HttpRequest` interface looks like this:

```ts
export interface HttpRequest {
    method: string | null;
    url: string;
    headers: {
        [key: string]: string;
    };
}
```

It's not possible to use the Application Insights client without casting the request object, which seems dirty.

**Comment by ejizba** [comment]
Hi folks we will get rid of `| undefined` in the types. If people want the strict type checking, they can turn on [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) in their TypeScript config
