### ISSUE TITLE
Azure Functions TypeScript version

### ISSUE THREAD

**Issue by ruheni** [Azure/azure-functions-nodejs-worker#382]
Hello folks 👋🏾

Awesome work with the Azure Functions. The experience is so much fun-c 🙂

I used the CLI to create a TypeScript serverless function. I noticed the typescript version used is `v3.3.3` in the devDependencies. Could this be updated to the latest version of TypeScript by default? 

I got errors when working with `@prisma/client` and could not start the functions, but after making the update, it worked smoothly.

**Comment by mhoeger** [comment]
Haha! Love the joke :) 

cc: @alrod - we updated our own types package too to use the latest version of typescript and are planning on updating the VS Code template to default to a higher version of TypeScript. This is a good issue to track that work. Thanks!

**Comment by ejizba** [comment]
VS Code was updated in https://github.com/microsoft/vscode-azurefunctions/pull/2712
The func cli was updated in https://github.com/Azure/azure-functions-core-tools/pull/2852
