### ISSUE TITLE
Setting node arguments on azure application settings dont work

### ISSUE THREAD

**Issue by zeyuri** [Azure/azure-functions-nodejs-worker#384]
#### Investigative information

Please provide the following:

- Function name(s) (as appropriate):
- Invocation ID: d5d9c46b-6775-41b3-bc6a-ad38491372c3
- Region: East US

#### Repro steps

1. Setup an application setting "languageWorkers__node__arguments=--experimental-loader @node-loader/core"
2. Hit the function

#### Expected behavior

The invoked function should run with the experimental loader args on the node invocation

#### Actual behavior

The application setting is ignored, thus causing a crash on the application

Here is a [link ](https://ssr-spa.azurewebsites.net/) for function url

#### Related information 

I've tried setting this node arguments in several ways, none did work. 

- "languageWorkers:node:arguments".This one works locally on the "local.settings.json" but the colon is not allowed on the applcation settings on azure.

I've found this instructions on this repo and on the azure docs, but none of them seem to work on the deployed version

**Comment by mhoeger** [comment]
Hi @zeyuri - this settings is currently only meant for local development, but we are working on addressing your issue in this work item: https://github.com/Azure/azure-functions-host/issues/7139

Please note too that setting `languageWorkers:node:arguments` in production will have a small negative performance impact on cold start, which is something that we should be sure to document (cc: @anthonychu and @alrod)

**Comment by zeyuri** [comment]
Thanks for the answer!

**Comment by mhoeger** [comment]
As a workaround - you can also set an app setting with key `WEBSITE_USE_PLACEHOLDER` and value `0`. However, this has an even more significant cold start performance impact and we typically don't recommend it. The PR linked above, once merge and deployed, will let you consume your custom "arguments" without `WEBSITE_USE_PLACEHOLDER=0`. See more context here: https://github.com/Azure/azure-functions-nodejs-worker/issues/348#issuecomment-733967555

**Comment by zeyuri** [comment]
I think I'm gonna try using containers
