### ISSUE TITLE
Handle all falsy values appropriately

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#388]
As @davidmrdavid, there are places where we do not treat falsy values as proper data and instead treat it as false. 

Example: https://github.com/Azure/azure-functions-nodejs-worker/pull/364

These need to be addressed and proper linting rules need to be put in place to prevent this issue in the future

**Comment by ejizba** [comment]
Minor details might still change, but overall this was addressed in https://github.com/Azure/azure-functions-nodejs-library/commit/9e6a842eec8d4d29e76604a331f641a260cd1501 as a part of the new programming model. I've started a doc here with more information: https://aka.ms/AzFuncNodeV4
