### ISSUE TITLE
recursive camelcase binding data

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-functions-nodejs-worker#39]

**Comment by mhoeger** [comment]
@mamaso if you're still checking - can you provide details :)

**Comment by mamaso** [comment]
Yep, the issue is well summarized in the host repo.

I added it here because I think it makes more sense to handle this in the language worker (as it's node specific behavior), rather than special casing it in the host.

One alternate possibility would be to have the camel case handled by the host automatically & a language worker describes to the host if it would like camel case or not in the json configuration that Chris whipped up.

**Comment by mhoeger** [comment]
You're the best Matt!! It'd be super nice to have formatting as a part of the language worker contract, but I lean towards your original suggestion of having binding data formatted by each language worker for cases like Python's lowercase_underscores (and for whatever other future languages we support). Thanks again!

**Comment by mhoeger** [comment]
Note: requires corresponding test change in azure-functions-host repo (https://github.com/Azure/azure-functions-host/issues/2571)

**Comment by mhoeger** [comment]
Updated details: the bug was that the keys in `context.bindingData` were camelCased one layer down but no further. 

**Before Fix:**
`context.bindingData.sys.MethodName` would be `HttpTriggerJS1`

**After Fix:**
`context.bindingData.sys.methodName` would be `HttpTriggerJS1`
