### ISSUE TITLE
Release v2 of TypeScript Typings

### ISSUE THREAD

**Issue by gidich** [Azure/azure-functions-nodejs-worker#398]
The NPM Types Package [@azure/functions](https://www.npmjs.com/package/@azure/functions) has not been updated with latest types in awhile.

For instance RetryContext (part of the system since 2.1) is not available.

**Comment by mkuklani** [comment]
We do not see this feature as mentioned above. It would be nice to be added to types

**Comment by heruwala** [comment]
Please prioritize this request, With types, it would help access the retry count property.

**Comment by kapoor1109** [comment]
NPM type package needs to be updated to the latest with the released codebase.

**Comment by nguyenduy** [comment]
It would be more stable and consistent if NPM type package is current with the released codebase.

**Comment by mogupta-ecfmg** [comment]
We need to access the retry count property to implement the desired retry logic. Please consider this on priority

**Comment by anthonychu** [comment]
@alrod Can you please take a look?

**Comment by PCOffline** [comment]
Bumping this! The timer input in the functions doesn't have a type either

**Comment by bm77525-kr** [comment]
Also interested in getting proper access to the retry context that now lives on the execution context property

**Comment by ejizba** [comment]
Hi folks - I just joined the team and will be focusing on the Node.js experience, including a lot of improvements to the TypeScript types. I would appreciate if you filed issues on this repo for any and all things you would like addressed in the types going forward. I've already started creating some issues myself - just take a look at the 'typescript-types' label for more information: https://github.com/Azure/azure-functions-nodejs-worker/issues?q=is%3Aissue+is%3Aopen+label%3Atypescript-types

I will use this issue to specifically track the release of v2 of the npm package. Anything else please file a new issue

**Comment by ejizba** [comment]
Hey all I've released v2.0.0-beta.0 of the types package. See here for release notes: https://github.com/Azure/azure-functions-nodejs-worker/releases/tag/types-v2.0.0-beta.0

If you have time to test it, please let me know if it works as-expected! Assuming there are no surprises, I plan to release an official version 2.0.0 very soon.

**Comment by ejizba** [comment]
v2.0.0 is out!
