### ISSUE TITLE
NodeJs Azure function  local variables per invocation

### ISSUE THREAD

**Issue by ssidnal** [Azure/azure-functions-nodejs-worker#412]
Trying to find an object in Azure Function NodeJs which can hold level variables per invocation.

something like res.locals in expressjs http://expressjs.com/en/5x/api.html#res.locals

Please suggest if there is any other way in which I can have local variables per execution with azure functions.

**Comment by ejizba** [comment]
Hi @ssidnal we're not super familiar with the benefits and nuances of using res.locals vs standard variables. Can you either give an example and/or describe why you want this functionality?
