### ISSUE TITLE
Worker command line arguments 

### ISSUE THREAD

**Issue by Rapol** [Azure/azure-functions-nodejs-worker#415]
#### Question

Is there a way to pass command line arguments to the language worker? We use webpack and want to pass `--enable-source-maps` argument to the node process. I found this issue https://github.com/Azure/azure-functions-host/issues/2947 that has a merged PR but not sure if this is what Im looking for since no documentation in the azure docs mention this feature. 

For example, in AWS you can set an environment variable to pass args to the process https://docs.aws.amazon.com/lambda/latest/dg/runtimes-modify.html

**Comment by v-anvari** [comment]
Transferring this issue to node worker for more insights

**Comment by ejizba** [comment]
Sorry for the delay here. You should be able to use `languageWorkers__node__arguments` as an app setting or environment variable
