### ISSUE TITLE
Node process is making calls to Azure Files for package.json during cold start

### ISSUE THREAD

**Issue by safihamid** [Azure/azure-functions-nodejs-worker#449]
Cold Start profiles show calls directly to Azure files to try to read package.json file during specialization.
This happens even when content is deployed az zip and we are using zip cache.

Looks like node process looks at all these places to try to load the package.json file:

<HTML>
<BODY>
<TABLE><TR><TD>FileName</TD></TR><TR><TD>C:\Program Files (x86)\SiteExtensions\Functions\4.0.0\workers\node\dist\src\package.json</TD></TR><TR><TD>C:\Program Files (x86)\SiteExtensions\Functions\4.0.0\workers\node\dist\package.json</TD></TR><TR><TD>C:\Program Files (x86)\SiteExtensions\Functions\4.0.0\workers\node\package.json</TD></TR><TR><TD>C:\Program Files (x86)\SiteExtensions\Functions\4.0.0\workers\package.json</TD></TR><TR><TD>C:\Program Files (x86)\SiteExtensions\Functions\4.0.0\package.json</TD></TR><TR><TD>C:\Program Files (x86)\SiteExtensions\Functions\package.json</TD></TR><TR><TD>C:\Program Files (x86)\SiteExtensions\package.json</TD></TR><TR><TD>C:\Program Files (x86)\package.json</TD></TR><TR><TD>C:\package.json</TD></TR><TR><TD>\\somestorage.file.core.windows.net\someappname\site\package.json</TD></TR><TR><TD>\\somestorage.file.core.windows.net\someappname\package.json</TD></TR></TABLE>

</BODY>
</HTML>

**Comment by alrod** [comment]
I am wondering if node tries to find package.json on the function code load:
https://github.com/Azure/azure-functions-nodejs-worker/blob/v2.x/src/FunctionLoader.ts#L47

**Comment by anthonychu** [comment]
I think this is standard behavior for Node. It uses package.json to figure out things like module system type (commonjs or module) and it'll search all parents to find it. It's searching from that location because workers\node\dist\srcnodejsWorker.js is the entry point. Not sure if we can prevent this but can probably limit it to a single read if we include a package.json in workers\node\dist\src.

**Comment by alrod** [comment]
To prove the theory I did not load function from file system but instead loaded hardcoded function from memory. It looks like we need some "empty" package.json added to the worker so it will be loaded from worker folder before going to AzureFiles:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/2578359/139354343-5e025927-8158-48ec-bd21-e1561e4b6a09.png)

@safihamid validated that it works:
[etls.zip](https://github.com/Azure/azure-functions-nodejs-worker/files/7438057/etls.zip)

**Comment by ejizba** [comment]
~~Addressed in https://github.com/Azure/azure-functions-host/pull/7948~~

**Comment by ejizba** [comment]
Fixed in https://github.com/Azure/azure-functions-nodejs-worker/pull/501
