### ISSUE TITLE
Support Node.js v16 LTS

### ISSUE THREAD

**Issue by aaronadamsCA** [Azure/azure-functions-nodejs-worker#454]
Node.js v16 is the current long-term support release.

Azure Functions doesn't even appear to have an announced support timeline for it.

Is Azure Functions a dead product? What's going on here?

**Comment by ejizba** [comment]
Hi @aaronadamsCA I've just transferred another issue to this repo which covers the same topic. Please see https://github.com/Azure/azure-functions-nodejs-worker/issues/455 for more information
