### ISSUE TITLE
Uncaught exceptions crash the worker with no error messages

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-nodejs-worker#51]
Repro:

Send a message greater than 4MB in size. Host will crash with no errors to logs.

Expected behavior:

Host should gracefully handle unhandled exceptions. It should attempt to log them to the host and stderr.

**Comment by mhoeger** [comment]
I think this issue is too broad to be actionable. The specific example has been moved here: https://github.com/Azure/azure-functions-host/issues/2840
