### ISSUE TITLE
Feature - an SDK to improve testing experience

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-nodejs-worker#515]
There are some challenges that exist today when testing Node.js Azure Functions, especially when using TypeScript. It might be useful to publish a library/SDK to help with testing.

## Unit testing

When writing unit tests, we need to create mocks for context, request, response, logger, etc. This is especially difficult in TypeScript because the mocks must provide all properties/functions to satisfy the interfaces even if they're not being used.

Proposal: SDK to provide mock objects for common types used in functions.

## Integration / end-to-end testing

When writing E2E tests, it would be great to be able to launch Azure Functions Core Tools and test the app by making HTTP requests, sending queue messages, etc.

Proposal: SDK to provide a [Puppeteer-like](https://github.com/puppeteer/puppeteer#usage) API to programmatically launch and manage Core Tools:
- Use it to start/stop an instance either before/after entire test run, each test suite, or each test
- Ability to pass in different environment variables and settings when launching

Related: https://github.com/Azure/azure-functions-nodejs-worker/issues/120, https://github.com/Azure/azure-functions-nodejs-worker/issues/295

**Comment by timtucker-dte** [comment]
Not sure if you'd find it helpful, but at least for logging, the solution I'd come up with was relatively simple.

instead of calling:
`
context.log.info("Some message")
`

I have a function that logs to context if available and to console.log if it isn't -- this way functions that only rely on passing in context for logging work without any issues if I just pass undefined as the context in unit tests:
`
function logInfo(context: Context, ...args: unknown[]) {
    const logger = context?.log?.info || console.log;
    logger.logInfo(...args);
}
`

**Comment by ejizba** [comment]
This [was improved](https://github.com/Azure/azure-functions-nodejs-library/commit/068dcf43f565f5c9052125d9e39379cd99f7ee87) as a part of the new model. See [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-node-upgrade-v4?tabs=v4#create-a-test-context) as an example. Users should be able to create a context, http request, etc. from the new sdk even in a unit test environment.

In terms of the puppeteer-like API to run e2e tests, I'm skeptical we would do that without a lot more demand from users. We have our own e2e tests and it didn't feel too difficult to manage core tools: https://github.com/Azure/azure-functions-nodejs-e2e-tests/blob/main/src/global.test.ts. Regardless, if folks still want the e2e improvements I'd prefer to track that separately form unit tests.
