### ISSUE TITLE
Add entrypoint for app-level code

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-nodejs-worker#537]
UPDATE: Per the final design, you can specify a single file or a glob pattern for multiple files as the "main" field in your "package.json" file.

---

Basically, provide a way for users to run app-level code when the worker is initialized. This would be directly beneficial for the new hooks feature (#522), but could realistically be used for any arbitrary code. Current proposal is to respect the [main](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#main) field in a user's package.json

NOTE: I already added the function app dir to the worker init request in https://github.com/Azure/azure-functions-host/pull/8144, necessary to read the user's package.json

**Comment by aaronpowell** [comment]
With the change on the Function Host, will there be some more data provided to the workers when they start up, info that can be used to find the `package.json`?

**Comment by ejizba** [comment]
Yes that is the point of the change on the host and it will also help with https://github.com/Azure/azure-functions-nodejs-worker/issues/531, if that's what you're after 😝

**Comment by aaronpowell** [comment]
> Yes that is the point of the change on the host and it will also help with #531, if that's what you're after 😝

![MaaaaybeGIF](https://user-images.githubusercontent.com/434140/154396422-888759d3-f8d9-499f-9e2a-ca93705de7c2.gif)
