### ISSUE TITLE
Provide startup/teardown hooks

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-nodejs-worker#539]
Related to https://github.com/Azure/azure-functions-nodejs-worker/issues/522, which is focused on invocation hooks (needed for distributed tracing), there is benefit to startup & teardown hooks as well

A few differences between putting code at the top level of the startup file vs. a startup hook:
1. Startup hooks can use `await` (commonjs files don't support top level `await`, although es6 does)
2. Startup hooks can be passed a context object with extra information about the worker

**Comment by hossam-nasr** [comment]
Startup hooks added in #577. Teardown hooks tracked by #606. Closing this issue
