### ISSUE TITLE
Entire host crashes if >=1 function throws an exception on initialization

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#56]
"result" of GRPC StatusResult message must be string (not exception). We should not be setting an exception object to be "result", which expects a string (here: https://github.com/Azure/azure-functions-nodejs-worker/blob/58ea3456af16e5ca87b2439e7a7d2172ff4bb868/src/WorkerChannel.ts#L82)

Similar issues may be occurring where grpc message components have mismatched types.

Related to: https://github.com/Azure/azure-functions-host/issues/2510

**Comment by willmorgan** [comment]
Has the fix for this been released as part of any incremental release that we can use?

**Comment by mhoeger** [comment]
It was a part of this deployment that unfortunately had to be canceled: https://github.com/Azure/app-service-announcements/issues/105

**Comment by mhoeger** [comment]
This change will be a part of our next deployment! You could deploy the [functions runtime as a private site extension](https://github.com/Azure/azure-functions-host/wiki/Deploying-the-Functions-runtime-as-a-private-site-extension) if you need it now? You'd want to use this source code: https://github.com/Azure/azure-functions-host/releases/tag/v2.0.11737-alpha
