### ISSUE TITLE
Support Node 18

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-nodejs-worker#562]
Initial release: 2022-04-19
Active LTS start: 2022-10-25

https://nodejs.org/en/about/releases/

**Comment by ejizba** [comment]
Node.js 18 on Azure Functions is now supported in public preview 😊🎉

https://azure.microsoft.com/updates/public-preview-nodejs-18-in-azure-functions/

**Comment by BrandonSchreck** [comment]
Is there an ETA on when Node.js v18 and Azure Functions v4 will be ready for general availability?

**Comment by ejizba** [comment]
Hi @BrandonSchreck our goal is December, but due to the holidays it may end up being January.

You can check here for the latest estimate on our timeline:
https://github.com/Azure/azure-functions-nodejs-worker/wiki/Roadmap

**Comment by BrandonSchreck** [comment]
Thank you @ejizba

**Comment by ejizba** [comment]
https://azure.microsoft.com/updates/generally-available-azure-functions-support-for-nodejs-18/

🎉🎉🎉
