### ISSUE TITLE
originalUrl does not exist on type HttpRequest interface in Typescript definition

### ISSUE THREAD

**Issue by SikoSoft** [Azure/azure-functions-nodejs-worker#589]
The definition for the originalUrl property is missing from the HttpRequest interface, resulting in "Property 'originalUrl' does not exist on type 'HttpRequest'.ts(2339)" errors.

#### Investigative information

Not relevant. This is a development issue that is easy to observe when attempting to use this property in Typescript.

#### Repro steps

Provide the steps required to reproduce the problem:

1) Refer to req.originalUrl anywhere when working with an HttpRequest in typescript.
2) Note the error.

#### Expected behavior

No red squiggly error suggesting the property doesn't exist, when it in fact does exist.

#### Actual behavior

The IDE will throw an error, underline "originalUrl" suggesting it is not valid, and the Typescript compiler will error out saying you are referring to a property that does not exist.

#### Known workarounds

Use Javascript or type "any".

#### Related information 

https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=v2-v3-v4-export%2Cv2-v3-v4-done%2Cv2%2Cv2-log-custom-telemetry%2Cv2-accessing-request-and-response%2Cwindows-setting-the-node-version

**Comment by ejizba** [comment]
Hmm it looks like `originalUrl` and `url` should have the [same value](https://github.com/Azure/azure-functions-nodejs-worker/blob/1b517a73117a99b0d58f050dcccb9f89709adac4/src/http/Request.ts#L35). In the short term, you can just use `url` and that should fix any errors you see. It's a bit weird that `url` is listed in the types, but `originalUrl` is listed in the docs, though.

I'll add this to our backlog, but if you want a fix fast, feel free to contribute yourself: https://github.com/Azure/azure-functions-nodejs-worker#contributing-to-typescript-type-definitions

**Comment by SikoSoft** [comment]
Interesting...

Yeah, I saw the url definition and wondered what the difference is.

After initial testing, it appears to provide the same value, so I will update my code and start using this property.

Thanks for the info!
