### ISSUE TITLE
Detector for incompatible packages

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-functions-nodejs-worker#593]
- [Add a detector to let customers know that they are importing incompatible packages with their apps](https://dev.azure.com/Azure-Functions-Supportability/IPD%20Reduction%20-%20Copper/_boards/board/t/IPD%20Reduction%20-%20Copper%20Team/Feature%20Areas/?workitem=644)

**Comment by ejizba** [comment]
This was closed a while ago: https://dev.azure.com/Azure-Functions-Supportability/IPD%20Reduction/_workitems/edit/644
