### ISSUE TITLE
Detector for catching timeouts 

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-functions-nodejs-worker#594]
- [Check if detector catches timeout exceeding the limit](https://dev.azure.com/Azure-Functions-Supportability/IPD%20Reduction%20-%20Copper/_boards/board/t/IPD%20Reduction%20-%20Copper%20Team/Feature%20Areas/?workitem=645)

**Comment by ejizba** [comment]
This was closed a while ago: https://dev.azure.com/Azure-Functions-Supportability/IPD%20Reduction/_workitems/edit/645

In favor of a more generic issue, which is also closed as done:
https://dev.azure.com/Azure-Functions-Supportability/IPD%20Reduction/_workitems/edit/607
