### ISSUE TITLE
Detector for unsupported language version and version formatting

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-functions-nodejs-worker#595]
- [Detecting unsupported language version given Functions runtime, and correct formatting of versions](https://dev.azure.com/Azure-Functions-Supportability/IPD%20Reduction%20-%20Copper/_boards/board/t/IPD%20Reduction%20-%20Copper%20Team/Feature%20Areas/?workitem=672)

**Comment by ejizba** [comment]
This was fixed a while ago

https://dev.azure.com/Azure-Functions-Supportability/IPD%20Reduction/_workitems/edit/672
