### ISSUE TITLE
Increase grpc max message size

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#60]
Sending an message that was too caused an uncaught exception to be thrown and the worker to shut down. Afterwards, the host shutdown. This may be due to an unrelated timeout error, but should be verified.

`Worker xxxx encountered event stream error:  { Error: Received message larger than max (5852896 vs. 4194304)`
`Worker xxxx uncaught exception:  { Error: Received message larger than max (5852896 vs. 4194304)`

**Comment by mhoeger** [comment]
Issue moved to https://github.com/Azure/azure-functions-host/issues/2677

**Comment by pragnagopa** [comment]
Let’s keep this one open to update grpc message size on the client side. Also, let’s catch this exception and log friendly message if the message exceeds the one we set

**Comment by pragnagopa** [comment]
Here is the documentation on channel options to set max_receive_message_length and max_send_message_length https://grpc.io/grpc/csharp/api/Grpc.Core.ChannelOptions.html
