### ISSUE TITLE
Worker was unable to load entry point

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-nodejs-worker#630]
With the rollout of host version 4.12 users can see this error:

> Worker was unable to load entry point "index.js": Found zero files matching the supplied pattern

NOTE: The filename in the message may be different, but "index.js" is by far the most common.

### Mitigation

Update: The change was rolled back in host v4.12.2.19454. No further mitigation should be necessary.

### Background

We introduced a new feature in https://github.com/Azure/azure-functions-nodejs-worker/issues/537 that lets users run app-level entrypoint code. By default we would load the file specified in a user's package.json "main" field and throw an error if we have any issues loading the file specified. Unfortunately, many existing users appear to have "main" set to "index.js" but that file does not exist in their app. When we started rolling out this feature, that means their app would fail to start.

**Comment by bradoyler** [comment]
I am seeing this error with Functions Runtime 4.31.0.22173 when we upgrade from Node v16 to Node v20.

**Comment by ejizba** [comment]
Hi @bradoyler this was a by-design breaking change for Node v20. You have to fix the error for your app to run (and it should be relatively easy to fix). See https://github.com/Azure/azure-functions-nodejs-worker/issues/697 for more info
