### ISSUE TITLE
Fix worker metadata format

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-nodejs-worker#633]
We'd like to be more strict about format for the analytics team.

We currently see this in the metrics table:

```
"RuntimeName": node,
"RuntimeVersion": v16.16.0,
"WorkerVersion": 3.5.0,
"WorkerBitness": ia32
```

Is it possible to remove the version prefix ("v") from runtimeVersion?
We also noticed the bitness looks wrong: "ia32" which should be "x86"

**Comment by ejizba** [comment]
> We also noticed the bitness looks wrong: "ia32" which should be "x32"

It's debatable what is "wrong" or right. Here's [one stackoverflow post](https://stackoverflow.com/questions/53364320/the-most-correct-way-to-refer-to-32-bit-and-64-bit-versions-of-programs-for-x86) discussing some differences. Assuming you're used to windows terminology, I think it's saying ia32 is the same as x86, but not x32. In any case, here is the [list of possible arch values](https://nodejs.org/api/process.html#processarch) given to us by Node.js and I'd rather not manipulate those if we don't have to

> Is it possible to remove the version prefix ("v") from runtimeVersion?

Similar to above, we're just passing along the version given to us by Node.js so I'd prefer not to modify it. Sure we could remove the 'v', but couldn't the analytics team do that as well? It just feels risky if the analytics team is going to rely on these properties being in a strict format across all workers

**Comment by liliankasem** [comment]
Thanks for the info, that's totally fair and makes sense to me. I think the goal was to make this easier for the analytics team for the adoption dashboard this data is going to be used for.

cc: @fabiocav @cloudmelon @jcookems FYI

**Comment by jcookems** [comment]
@ejizba, I think you summed it up well: should each layer pass along what the previous one gives us, or should some layer "fix" the value to make them consistent? (The Analytics will follow your example and "just pass along the version given to us" and have the next layer handle it, the dashboard in this case)

@liliankasem, I think the only reason we'd want enforce consistency would be if the Functions team wants to look at things like `workerBitness` across runtimes in the resulting dashboards. We might need to get Melony's input on this.
 It doesn't make sense to compare versions across runtimes. In general, I'd expect that each runtime's records would only be compared with other records for the same runtime, so cross-runtime diffs probably wouldn't by problematic. 

If consistency is needed, it should happen at the lowest level, where the details like Node.js's "list of possible arch values" are known, instead of relying on a third-party (Analytics) to grok those details for *all* Functions runtimes.

**Comment by ejizba** [comment]
@lilyjma will sync with the PM team on this as it seems like a problem for all languages

**Comment by fabiocav** [comment]
@lilyjma let's follow up on this issue. We're trying to have items associated with this feature closed out.

**Comment by lilyjma** [comment]
Replied to existing email thread about this. I think this is a cross language question that needs the other language's input as well.

**Comment by liliankasem** [comment]
@cloudmelon any updates on how this issue is going? Has there been an agreement on format across language workers?

**Comment by cloudmelon** [comment]
Yes. I spoke with Lily and she agreed to align with us and will follow up with Eric,

Kind regards
Melony
________________________________

**Comment by ejizba** [comment]
I updated the version to remove the 'v' here: https://github.com/Azure/azure-functions-nodejs-worker/pull/658. That one was easy enough so I just did it

The bitness is more complicated with nuances between .NET and Node.js, so we haven't had a compelling enough reason to work on that. After following up with me, @lilyjma started an offline thread with @fabiocav and @cloudmelon a few months ago but it did not receive a response.

Perhaps if you explained how this data is meant to be used outside of the worker teams that would be more compelling? My general view is that this information is most helpful for the language worker crew (tracking their own telemetry, investigating incidents, etc.), in which case it would be best (and easiest) to keep it in the language’s “native” format.

**Comment by cloudmelon** [comment]
> I updated the version to remove the 'v' here: #658. That one was easy enough so I just did it
> 
> The bitness is more complicated with nuances between .NET and Node.js, so we haven't had a compelling enough reason to work on that. After following up with me, @lilyjma started an offline thread with @fabiocav and @cloudmelon a few months ago but it did not receive a response.
> 
> Perhaps if you explained how this data is meant to be used outside of the worker teams that would be more compelling? My general view is that this information is most helpful for the language worker crew (tracking their own telemetry, investigating incidents, etc.), in which case it would be best (and easiest) to keep it in the language’s “native” format.

hi @ejizba i had a very long convo with @lilyjma about this, and I thought she talked with you already. Hi @lilyjma were you able to follow up on this ( after our convo a while back ) ? thanks!

**Comment by liliankasem** [comment]
> > I updated the version to remove the 'v' here: #658. That one was easy enough so I just did it
> > The bitness is more complicated with nuances between .NET and Node.js, so we haven't had a compelling enough reason to work on that. After following up with me, @lilyjma started an offline thread with @fabiocav and @cloudmelon a few months ago but it did not receive a response.
> > Perhaps if you explained how this data is meant to be used outside of the worker teams that would be more compelling? My general view is that this information is most helpful for the language worker crew (tracking their own telemetry, investigating incidents, etc.), in which case it would be best (and easiest) to keep it in the language’s “native” format.
> 
> hi @ejizba i had a very long convo with @lilyjma about this, and I thought she talked with you already. Hi @lilyjma were you able to follow up on this ( after our convo a while back ) ? thanks!

I'll let Lily follow up with more details here but the tl;dr is that the analytics team is using this data to create an adoption dashboard; last I heard is that the data is not reliable enough to start ingesting. We're working to make sure all the workers follow the same data format/contract to unblock this.
