### ISSUE TITLE
[Premium] - How azure rks?

### ISSUE THREAD

**Issue by rahul-adpushup** [Azure/azure-functions-nodejs-worker#636]
Xjdjd

**Comment by ramya894** [comment]
@rahul-adpushup We will check this issue internally and update you with more insights.

**Comment by ramya894** [comment]
@rahul-adpushup
[Sharing Your Function App name privately] (https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)
@ejizba Could you please have look at this issue, once we get the input from user.

**Comment by ejizba** [comment]
> As per my understanding, as the batchSize is 1, azure should launch a new VM for each function and there shouldn’t be a delay.

This is not the case, it will share a VM in most cases. Your `functionTimeout` is set to 59 minutes, which is the exact delay you are seeing between messages. To me, that means something in your function is causing it to hang and do nothing for about an hour, preventing future messages from being processed.

If you're still having issues, please let me know and share the function app name privately as mentioned above so I can take a closer look at the logs.

**Comment by rahul-adpushup** [comment]
Dudid
