### ISSUE TITLE
Node 10 support

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#66]
Although Node 8 is under long-term support, Node 9 is current. Any install via brew or chocolatey will default to Node 9, which creates a bad experience for local developers that install node for the first time on a machine and must downgrade to 8.

UPDATE: node 10 just released

**Comment by mhoeger** [comment]
We want to update to (at least) `node-pre-gyp@0.10.0` and `grpc@1.11.3`

There's an error in grpc's index.d.ts file that keeps us from being able to use `protobufjs@6.7.0` in the same project: https://github.com/grpc/grpc-node/issues/176

**Comment by ahmelsayed** [comment]
why is this breaking? Does it mean we will drop node 8?

**Comment by mhoeger** [comment]
I don't think we've decided whether or not we're keeping node 8 as a backup (likely yes? @paulbatum), but we definitely will be changing the default version to 10

**Comment by ahmelsayed** [comment]
thanks @mhoeger I was asking in the context of the email thread about handling `WEBSITE_NODE_DEFAULT_VERSION`, I'll respond on that thread

**Comment by mhoeger** [comment]
re-opening to track pulling to functions-host repo
