### ISSUE TITLE
context.debug threw error

### ISSUE THREAD

**Issue by toyip-fadv** [Azure/azure-functions-nodejs-worker#682]
Try to use context.debug and got the following exception    

Node 18v and Azure function version 2.0 

2023-05-02T15:00:00.934Z] Exception: context.debug is not a function
[2023-05-02T15:00:00.934Z] Stack: TypeError: context.debug is not a function
[2023-05-02T15:00:00.934Z]     at module.exports

here is a host.json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    },
    "console": {
      "isEnabled": true
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.3.0, 4.0.0)"
  },

```node
export default (context, req) => {
  
    context.debug('index.js - main Function');  <-- throws error here.
 
```

**Comment by ejizba** [comment]
Hello, `context.debug` is only available in the new preview v4 programming model. You can read more about that here: https://learn.microsoft.com/en-us/azure/azure-functions/functions-node-upgrade-v4?tabs=azure-cli-set-indexing-flag%2Cv4

Are you using v4? If so, you would see `@azure/functions` listed as a dependency in your package.json pointing to version `4.0.0-alpha.9` or something similar.
