### ISSUE TITLE
Javascript function with service bus trigger delivering byte message

### ISSUE THREAD

**Issue by piotr-napadlek** [Azure/azure-functions-nodejs-worker#684]
Hi, we have a case when we want to process a byte array message within javascript function. The handler code though receives the message only as a string, ie. even when the message is a byte array the call to `typeof message` returns string.

We tried to convert that string back to byte array, but upon investigating we've discovered it contains several UTF-8 replacement characters ie. 0xEF 0xBF 0xBD rendering our data lossy. I haven't found any docs on how to switch the implementation to receive a Uint8Array or any structure supporting raw byte message.

Is there any option that I can handle my use case?

**Comment by ejizba** [comment]
Hi if you're using model v3, you can set `"dataType": "binary"` in your `function.json` file. Here's an example:
```json
{
  "bindings": [
    {
      "name": "mySbMsg",
      "type": "serviceBusTrigger",
      "direction": "in",
      "queueName": "myinputqueue",
      "connection": "SERVICEBUS_APPSETTING",
      "dataType": "binary"
    }
  ]
}
```

If you're using model v4, that's not supported yet. Tracked by https://github.com/Azure/azure-functions-nodejs-library/issues/72

**Comment by piotr-napadlek** [comment]
Thanks, will track the other issue then.
