### ISSUE TITLE
Global `require` overwriting doesn't play nice with applicationinsights 2.5.1+

### ISSUE THREAD

**Issue by CreativeTechGuy** [Azure/azure-functions-nodejs-worker#685]
Full details of issue here: https://github.com/microsoft/ApplicationInsights-node.js/issues/1144

#### Repro steps

Provide the steps required to reproduce the problem:

1. Use Node.js [applicationinsights](https://www.npmjs.com/package/applicationinsights) v2.5.1+ autocollection feature in an Azure Function. Log the return value of `appinsights.getCorrelationContext()` in the app which will make the problem later easier to see.
2. Run the Azure Function locally with `azure-functions-core-tools`
3. `getCorrelationContext()` will return null
4. Downgrade applicationinsights to 2.5.0
5. `getCorrelationContext()` will return the expected value

#### Details

Please see the linked issue above which has a full trace of the problem. This is a problem with multiple packages overwriting globals and not playing nice with each other. Both packages can probably do something to improve the situation and make this sort of issue less likely to occur. Neither package is an issue on its own, but when both try to overwrite the same global in different ways, the issue appears.

**Comment by ejizba** [comment]
I took a look and commented on the linked issue. This has already been fixed in `require-in-the-middle` and we just need to wait for the fix to propagate through the dependencies.

As mentioned, the current suggested workaround is to downgrade the `applicationinsights` package to v2.5.0

**Comment by dzoba** [comment]
> I took a look and commented on the linked issue. This has already been fixed in `require-in-the-middle` and we just need to wait for the fix to propagate through the dependencies.
> 
> As mentioned, the current suggested workaround is to downgrade the `applicationinsights` package to v2.5.0

How do we do this?  I don't see `applicationinsights` in package.json

**Comment by ejizba** [comment]
What about in your "package-lock.json" file? Do you see `require-in-the-middle` or `applicationinsights` listed?

An easy way to update your dependencies is to run `npm update`

**Comment by ejizba** [comment]
Just tested and this no longer a problem for me with the latest version of applicationinsights
