### ISSUE TITLE
A function can only be registered during app startup.

### ISSUE THREAD

**Issue by wojtekmaj** [Azure/azure-functions-nodejs-worker#718]
#### Investigative information

Please provide the following:

- Timestamp: 2023-09-19 10:29:56.372
- Function App name: nedx-fa-dev-jotform
- Function name(s) (as appropriate): get
- Invocation ID: Not sure what it is, maybe 2d31f818-2b46-47df-ba55-9cf3057aa71d?
- Region: West Europe

#### Repro steps

I have created a simple v4 Azure Function:

```
import { app } from '@azure/functions';

app.http('get', {
  methods: ['GET'],
  handler: async (req) => {
    return {
      status: 200,
      body: 'Hello world (from get)',
    };
  },
});
```

I then compiled it with TypeScript.

I have added `function.json` with manually defined triggers, because otherwise I got "No HTTP triggers found." error.

```
{
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": ["get"]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ],
  "scriptFile": "dist/index.js"
}
```

I renamed dist/index.js to dist/index.mjs, because Azure Functions apparently can't properly import ESM modules even if type: module is set in package.json unless they have .mjs extension.

#### Expected behavior

Hello world

#### Actual behavior

Result: Failure Exception: Worker was unable to load function get: 'A function can only be registered during app startup.' Stack: Error: Worker was unable to load function get: 'A function can only be registered during app startup.' at Object.t.registerFunction (/azure-functions-host/workers/node/dist/src/worker-bundle.js:2:28273) at generic (/home/site/wwwroot/get/node_modules/@azure/functions/dist/azure-functions.js:494:17) at Object.http (/home/site/wwwroot/get/node_modules/@azure/functions/dist/azure-functions.js:428:5) at file:///home/site/wwwroot/get/dist/index.mjs:2:5 at ModuleJob.run (internal/modules/esm/module_job.js:183:25) at async Loader.import (internal/modules/esm/loader.js:178:24)

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used: TypeScript
* Links to source: n/a
* Bindings used: I really don't know - app.http('get', …) thing didn't work, so I guess that would be the config from function.json pasted above?

**Comment by wojtekmaj** [comment]
Compiled it down to CJS, removed the .mjs rename hack + type: module, and got same error back.

**Comment by ejizba** [comment]
Hi @wojtekmaj looks like you're using a mix of the v3 and v4 models. In the v4 model, you do _not_ need the "function.json" file. So the real error we need to fix is "No HTTP triggers found."

If you're running locally, make sure you have `"AzureWebJobsFeatureFlags": "EnableWorkerIndexing"` set in your `local.settings.json` file. That's probably the most common problem we see, but if you created your project from VS Code or core tools it should already be set for you.

If that doesn't help, please share the logs from running `func start`. That'll tell me your func version and any other warnings/errors you might be getting

**Comment by wojtekmaj** [comment]
I think I've figured it out. It was running Node 14 on Azure side for reasons unknown to me, and this caused all sorts of problems. On Node 18 everything's fine.
