### ISSUE TITLE
Support Node 20

### ISSUE THREAD

**Issue by itpropro** [Azure/azure-functions-nodejs-worker#724]
Node 20 is the current LTS version of Node and should be supported. This impacts

- App Service
- Azure Functions
- Static Web Apps

Node 18 is only receiving security updates at this point and Node 16 is completely EOL and should therefor be removed as supported version.

**Comment by ejizba** [comment]
Hi @itpropro, I only work on Azure Functions, but we already support Node 20 in preview and you can see the latest estimates for GA on our roadmap here: https://github.com/Azure/azure-functions-nodejs-library/wiki/Roadmap

Closing as duplicate of https://github.com/Azure/azure-functions-nodejs-library/issues/170
