### ISSUE TITLE
Azure Functions in a monorepo (Node.js)

### ISSUE THREAD

**Issue by diberry** [Azure/azure-functions-nodejs-worker#727]
If I have 2 or more functions app in a monorepo, where there is a single node_modules folder, do all functions apps have to be on the same @azure/functions version. This seems reasonable -- is it stated in the docs? 

@ggailey777 ?

**Comment by ejizba** [comment]
We don't have any docs or recommendations on monorepos - generally you can do whatever you want. You can only use one @azure/functions version _per app_ (which we document in [several places](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=javascript%2Clinux%2Cazure-cli&pivots=nodejs-model-v4#considerations)), but that has nothing to do with monorepos
