### ISSUE TITLE
Settings on serviceBus.clientRetryOptions is not upheld for serviceBusTopic triggers on the node worker

### ISSUE THREAD

**Issue by JorgenSQ** [Azure/azure-functions-nodejs-worker#730]
#### Investigative information

- Timestamp: 2024-01-21T13:31:12Z
- Function App name: *****-checkin-integration
- Function name(s) (as appropriate): ProcessOrderToJunglemap
- Invocation ID: 2a09e28a0f16c3685538d6c601ff5bee (Operation Id)
- Region: Europe West

#### Repro steps

1. build basic version of `serviceBusTopic` template
2. connect it two a queue
3. Configure `host.json` with the following settings: 

```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensions": {
    "serviceBus": {
        "clientRetryOptions":{
            "mode": "exponential",
            "tryTimeout": "00:05:00",
            "delay": "00:00:10.00",
            "maxDelay": "00:10:00",
            "maxRetries": 3
        }
      }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[4.0.0, 5.0.0)"
  }
}

```

#### Expected behavior

When configuring the retryOptions as above, you would expect the service bus client in the function to wait 10 seconds the first time it fails before retrying.

#### Actual behavior

It retries all times immediatly, violating both the "delay" and "maxRetries" setting (none of the settings work). 

#### Known workarounds

Provide a description of any known workarounds.

None
#### Related information 

None

**Comment by ejizba** [comment]
Hi @JorgenSQ Can you give more details on what you're trying to retry? For example I think those settings are somewhat limited in scope based on [these docs](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus?tabs=isolated-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-javascript):

> The clientRetryOptions settings only apply to interactions with the Service Bus service. They don't affect retries of function executions.
