### ISSUE TITLE
Node.js v4 migration - .funcignore additiona of .tsconfig.json

### ISSUE THREAD

**Issue by dfberry** [Azure/azure-functions-nodejs-worker#734]
Why is the tsconfig.json now in the .funcignore file? 

@glaucia86 fyi

**Comment by khkh-ms** [comment]
It will be transferred to functions node repo.

**Comment by ejizba** [comment]
We generally assume most projects will build before deploying, so build-related files (like tsconfig.json, *.ts files, etc.) are excluded to keep the deploy clean/small. Of course people are free to configure this differently - if they are doing a remote build they would probably remove these

**Comment by dfberry** [comment]
I think it was interfering with a sample project but now that its been so long and I'm not seeing it now - maybe the project compensated for it. Any way, thanks for answering.
