### ISSUE TITLE
Warmup Trigger not working with Node.js Function Apps

### ISSUE THREAD

**Issue by lorenzadomat** [Azure/azure-functions-nodejs-worker#762]
I am trying to add a [Warmup Trigger](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-warmup?tabs=isolated-process%2Cnodejs-v4&pivots=programming-language-javascript) to my function app, but I doesn´t get executed during scale-out.
For testing purposes I have created a Function App with an Elastic Premium App Service Plan.
In the function app, I added the warmup trigger based on the examples from the documentation.
To trigger a scale-out operation of the function app, I manually increased the "Always ready instances" of the function app.

I tested the following scenarios:
- .NET Function App
  - Warmup Function has been triggered successfully during scale-out operation

- Node V3 & V4 Function App
  - Warmup Function has not been executed

Further information:
- in the Filesystem Logs I was able to see the following log messages, which at least indicate to me, that the function app should be able to work with the warmup trigger:
  -  Initializing Warmup Extension.
  - "WORKER_WARMUP_ENABLED": "1"
  - Found the following functions:Host.Functions.httpTrigger1Host.Functions.warmupTrigger1
  - Stopping the listener 'Microsoft.Azure.WebJobs.Extensions.Warmup.Trigger.WarmupTriggerBinding+NullListener' for function 'warmupTrigger1' (this happened after reducing the number of instances)
- Functions seem to be successfully loaded:
![Image](https://github.com/user-attachments/assets/1eb1824d-7997-4e7b-a621-31d70769667c)

warmup.js
```javascript
const { app } = require('@azure/functions');

app.warmup('warmupTrigger1', {
    handler: (warmupContext, context) => {
        context.log('Function App instance is warm.')
    },
});
```

host.json
```json
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[4.*, 5.0.0)"
  }
}
```

**Comment by earloc** [comment]
@lorenzadomat I remember that I stumbled over this on certain doc-pages and just had a lookup in the source...Does this start to work when you explicitly name your function `Warmup` (and maybe change the trigger-name also to `WarmupTrigger`)?

Over at https://github.com/Azure/azure-functions-host, there is some [explicit name-check](https://github.com/Azure/azure-functions-host/blob/bc21cd69782312508f95d85d60863b8881de2c11/src/WebJobs.Script/Host/ScriptJobHostExtensions.cs#L36) regarding **warmup** in place (not sure if this is responsible here, though)

From the docs, this matches for .NET functions:
- [isolated](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-warmup?tabs=isolated-process%2Cnodejs-v4&pivots=programming-language-csharp#tabpanel_1_isolated-process)
- [in-process](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-warmup?tabs=in-process%2Cnodejs-v4&pivots=programming-language-csharp#tabpanel_1_in-process)

All other samples for the different languages use the same naming, despite the one for [JavaScript on V4](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-warmup?tabs=in-process%2Cnodejs-v4&pivots=programming-language-javascript#tabpanel_2_nodejs-v4)...maybe this is just a missing doc / typo?

**Comment by lorenzadomat** [comment]
@earloc seems to work after renaming the function. Thanks for the hint 👍🏻
