### ISSUE TITLE
Non-string header values on http response throws error

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-nodejs-worker#78]
See details on the original issue reported here: https://github.com/Azure/azure-functions-host/issues/2768
Initial fix was to update RpcHttp proto file to <string, TypedData> dictionary. According to [HttpSpec](https://tools.ietf.org/html/rfc2616#section-4.2) header values are only valid ASCII characters. Need to fix NodeJS worker to convert to strings before sending message to functions host

**Comment by mhoeger** [comment]
Great! Thanks Pragna :)
