### ISSUE TITLE
Add stack trace to func host start import errors

### ISSUE THREAD

**Issue by arichiardi** [Azure/azure-functions-nodejs-worker#90]
Hi folks,
it seems like my worker starts fine with `func host start` but it then encounters a problem with my `.js` file.
Since it is compiled, I am not sure where it is breaking and not enough information is shown:

```
[6/6/18 11:37:59 PM] Worker was unable to load function init-store: 'SyntaxError: Unexpected token .'
[6/6/18 11:37:59 PM] Worker fa653417-0a2c-438d-8e6a-278d561bc95f malformed message functionLoadResponse.result.result: string expected
[6/6/18 11:37:59 PM] Worker fa653417-0a2c-438d-8e6a-278d561bc95f uncaught exception:  functionLoadResponse.result.result: string expected
[6/6/18 11:37:59 PM] Worker fa653417-0a2c-438d-8e6a-278d561bc95f exited with code 1
```

Is there a way to understand which line breaks? Or enable stack traces?

**Comment by mhoeger** [comment]
@arichiardi - would you mind sharing a code snippet? Seeing your function.json would also help, since your error is on function load.

**Comment by arichiardi** [comment]
The code snippet is ClojureScript compiled down to JS. Here is `function.json`:

```json
{
  "disabled": false,
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "request",
      "methods": [
        "POST"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "response"
    }
  ]
}
```

**Comment by arichiardi** [comment]
Is there a way to enable the stacktrace for the error?

**Comment by mhoeger** [comment]
awesome, thank you! we usually do have the stacktrace along with the error by default. i think you've hit a corner case where we likely don't handle our error gracefully.

**Comment by mhoeger** [comment]
I was able to repro your error. I don't know exactly how ClojureScript compiles down, but my guess is that your index.js looks something like this:
```
module.exports = {
   // Do cool stuff in JS
}
```

However, to work with the runtime, you should define module.exports equal to a function (can be async, as a side-note). `context` is not a global object as it differs per function execution, so you'll need to pass it in as a function parameter.

Your index.js should look like this, with at least context passed in as a param, but you could also add `request`. You can read more [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#exporting-a-function):
```
module.exports = function(context) {
   // Do cool stuff in JS
}
```

**Comment by arichiardi** [comment]
I will investigate more, but if I check the generated JS it looks similar to what you are writing:

```javascript
ep_cloud.init_store.http_handler = (function ep_cloud$init_store$http_handler(ctx,request){
 ...
}
```

**Comment by arichiardi** [comment]
I can confirm that node agrees:

```javascript
> const h = require("./init-store")
> h.toString()
'function ep_cloud$init_store$http_handler(ctx,request){
...
```

**Comment by arichiardi** [comment]
To add an additional data point. The lambdas work individually (I have three of them, I move two to a temp folder temporarily so that only one is loaded - that one works).

In any case I think the problem of this particular issue is that no stacktrace is provided, I will try to debug the other problem and open another issue in case.

**Comment by mhoeger** [comment]
are you using one single function.json for multiple functions ("lambdas") that you're trying to invoke? each trigger and entry point should have a corresponding [function.json](https://github.com/Azure/azure-functions-host/wiki/function.json).

one concept that's different from AWS lambda (if that's your background!) is the notion of a "function app" - which is a bundle of one or many functions. this can be especially helpful in trying to answer questions like "[should i do one big function or multiple smaller ones](https://forums.aws.amazon.com/message.jspa?messageID=703674)". But again, each function.json corresponds to one index.js entry point.

Here's an example of a valid file structure:
```    
    MyFunctionApp
    |     host.json
    |____ business
    |     |____ logic.js
    |____ function1
    |     |____ index.js
    |     |____ function.json
    |____ function2
          |____ index.js
          |____ function.json
```
**In "function1/index.js" and "function2/index.js"**
```
    var logic = require("../business/logic");

    module.exports = logic;
```
The function.json of function1 and function2 can be configured to different triggers.

**In "business/logic.js**
```
    module.exports = function (context, req) {
        // This is where shared code goes. As an example, for an HTTP trigger:
        context.res = {
            body: "<b>Hello World</b>",
            status: 201,
            headers: {
                'content-type': "text/html"
            }
        };     
        context.done();
    };
```

**Comment by mhoeger** [comment]
All this just as FYI / to help you in your debugging, we'll still fix printing a stack trace

**Comment by arichiardi** [comment]
Yep I am separating like the above but each index.js has basically in theory has its own runtime. So guess this was what I was trying to understand how different is the isolation of Azure lamdbas compared to AWS so thank you for opening the topic for me :smile:

In AWS requiring of the two lamdbas are required in their own node process so that you basically get process isolation effectively and statelessness.

I observed that in the case of `func` this does not hold true anymore: the two `index.js` files are required within the same node process.

Can you confirm that? It can be what causes my second issue.

**Comment by mhoeger** [comment]
In Azure Functions, you can think of a single function as a combination of a function.json + index.js script entry point. A "function app" is a group of functions and potentially other files of shared code. So each instance of a function app will run on the same process.

So yes, you're right! multiple functions can and do run on the same process

**Comment by mhoeger** [comment]
Note that in production, when your functions scale out, you may have multiple instances of function apps running, so multiple processes executing your code. So you shouldn't treat anything as truly global for preserving state, but you certainly can share code. or treat SDK objects, for example, as global.

**Comment by mhoeger** [comment]
Closing as issue was resolved on in azure-functions-host. The error message now shows that entry point must be indicated.
