### ISSUE TITLE
Fix DeprecationWarning: Buffer() 

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-nodejs-worker#98]
Using node 10, nodejs worker shows this warning:
```
     (node:11736) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
need to update nodejs worker to use Buffer.alloc()

**Comment by mhoeger** [comment]
Re-opening since we are reverting the fix, which was not interacting well with the functions host.
https://github.com/Azure/azure-functions-nodejs-worker/pull/119

Needs more investigation.

**Comment by mhoeger** [comment]
Closing as not seen and no details
